- .github/ISSUE_TEMPLATE/04_RPC_METHOD_REQUEST.md
> docs: add issue template

- rpc/Cargo.toml
- rpc/src/eth_rpc.rs
- rpc/src/lib.rs
- rpc/src/main.rs
> feat: change rpc skeleton to match reth's rpc architecture

- core/Cargo.toml
- core/src/helpers.rs
- core/src/lib.rs
- core/src/lightclient/mod.rs
- rpc/src/eth_rpc.rs
Implement eth_getBlockByNumber and eth_getBlockByHash
closes #16 
closes #24 
-
-
-
> feat: implement getBlockByNumber and getBlockByHash

- core/src/lightclient/mod.rs
- rpc/src/eth_rpc.rs
> feat: chain_id

- core/Cargo.toml
- core/src/lightclient/constants.rs
- core/src/lightclient/mod.rs
- core/tests/lightclient.rs
- rpc-call-examples/getCode.hurl
- rpc/Cargo.toml
- rpc/src/eth_rpc.rs
- rpc/src/lib.rs
- rpc/src/main.rs
- eth_blockNumber RPC Method implemented
- Implemented helper function for BlockId/BlockTag conversions
- Added automock test structure
- blockNumber first implementatino: 1.5 days
- AutoMock test structuring : 0.5 days
Issue Number: #20
-
-
-
> feat: Kakarot Rpc method "eth_getCode" + automock test structure

- core/src/helpers.rs
- core/src/lightclient/constants.rs
- core/src/lightclient/mod.rs
- core/tests/lightclient.rs
- rpc/Cargo.toml
- rpc/src/eth_rpc.rs
- rpc/tests/rpc.rs
> feat: first iteration of eth_call

- core/Cargo.toml
- core/src/helpers.rs
- core/src/lightclient/constants.rs
- core/src/lightclient/mod.rs
- core/src/lightclient/types.rs
- core/tests/lightclient.rs
- rpc-call-examples/blockByNumber.hurl
- rpc/src/eth_rpc.rs
> Feat: Changes to connect to metamask

- core/src/lightclient/mod.rs
- core/tests/lightclient.rs
- docs/methods/eth_syncing.md
- rpc/src/eth_rpc.rs
Implement eth_syncing
Time spent on this PR: 0.1 days
Unimplemented
Issue Number: #50
Returns the syncing status info
> Feat-syncing

- core/src/helpers.rs
- core/src/lightclient/mod.rs
- docs/methods/eth_getTransactionByBlockNumberAndindex.md
- rpc-call-examples/transactionByBlockNumberAndIndex.hurl
- rpc/src/eth_rpc.rs
eth_transactionByBlockNumberAndIndex returns a not implemented message
eth_transactionByBlockNumberAndIndex returns data
-
-
-
> implement eth_transactionByBlockNumberAndIndex, merge after pull

- .gitignore
- .markdownlint.json
- .prettierrc.json
- .vscode/settings.json
- README.md
Time spent on this PR: 0.5
No markdown linting
Added a markdownlint file, prettierrc and format the README
> doc: Format readme

- core/src/client/mod.rs
- core/src/helpers.rs
- core/src/utils/wiremock_utils.rs
2 hours
Closes #NUMBER_OF_ISSUE
-
-
-
> resolve merge conflicts for previous work to retrieve block hash and number for eth tx

- core/src/client/mod.rs
- core/src/helpers.rs
- rpc-call-examples/getTransactionReceipt.hurl
- rpc/src/eth_rpc.rs
- rpc/src/lib.rs
> feat: add logs handling in transaction receipt

- .github/.codecov.yml
> chore: disable codecov annotations

- .vscode/launch.json
No debug config
Added the debug config generated by VS code when using the [Code LLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) extension
Another debugging tool was suggested by VS Code that I didnt benchmark.
> Add debug config for use with lldb extension

- .github/workflows/test.yml
- rpc/tests/testing_utils.rs
Clippy is run in pre-commit but not check against in the CI
Added clippy --workspace --all-targes --all-features -- -D warnings
Fixed the existing errors
> Add clippy in ci

- core/src/client/mod.rs
Time spent on this PR: 1d
Closes #98
Using for loop on async not allowing executing them asynchronously
Using futures::stream allowing asynchronous execution of async
I was supposed to use join_all but during my research I found that streams were better suited for this as it allow asynchronous execution. 100% open to discussion though, I don't have a deep knowledge of rust yet
> feat: refactor async for loops using stream

- Cargo.toml
- crates/core/src/client/helpers.rs
- crates/core/src/client/mod.rs
- crates/rpc/tests/assert_helpers.rs
Time spent on this PR: 0.5
Closes #155 
-
-
-
> Rebase RETH dependencies

- crates/core/src/client/client_api.rs
- crates/core/src/client/mod.rs
- crates/core/tests/client.rs
- crates/rpc/src/eth_rpc.rs
Time spent on this PR: 0.1 d
Resolves: #182
> feat: add eth_transaction_by_hash

- Cargo.lock
- Cargo.toml
- crates/core/src/client/client_api.rs
- crates/core/src/client/errors.rs
- crates/core/src/client/helpers.rs
- crates/core/src/client/mod.rs
- crates/core/src/models/convertible.rs
- crates/core/src/models/mod.rs
- crates/rpc/src/eth_rpc.rs
Improve the current error handling, heavily inspired by the following reth code:
- [ETH RPC error codes](https://github.com/paradigmxyz/reth/blob/9e72cbf6b44fd195738c6d85f461304578c8156c/crates/rpc/rpc-types/src/eth/error.rs#L5)
- [Jsonrpsee ObjectError helper](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/result.rs#L159)
- [From implementation](https://github.com/paradigmxyz/reth/blob/9e72cbf6b44fd195738c6d85f461304578c8156c/crates/rpc/rpc/src/eth/error.rs#L81)
Error handling is a little messy and naming unclear.
Resolves: #NA
Error handling is regrouped into one file, with clear error codes.
- Renaming of `KakarotClientError` into `EthApiError`
- Regrouping of code into one file …
> feat: improve error handling

- Makefile
- crates/rpc/src/main.rs
- bring basic tracing back
- fix make commands
Tracing is not there, make commands `run` and `run-release` are broken.
Resolves: #191  #193 
- tracing is back 🥷 
- make commands work 🔨
> feat/fix: basic tracing & fix broken make commands

- crates/core/tests/client.rs
Comment was not a correct description of the test
Comment is now a correct description
-
-
-
- ✅  No
> clarify why we expect an error in failure test case of starknet event -> ethereum log conversion

- .github/workflows/test.yml
- Cargo.lock
- crates/core/src/client/client_api.rs
- crates/core/src/client/mod.rs
- crates/core/src/mock/wiremock_utils.rs
- crates/core/src/models/block.rs
- crates/core/src/models/convertible.rs
- crates/core/src/models/event.rs
- crates/core/src/models/transaction.rs
- crates/core/tests/client.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/eth_rpc.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/main.rs
- crates/rpc/tests/utils.rs
> refactor: rename kakarot client and kakarot client trait

- crates/core/src/client/mod.rs
- crates/core/src/models/convertible.rs
- crates/core/src/models/event.rs
- crates/core/tests/client.rs
use join_all in event looping
Time spent on this PR: 0.2
Resolves: #226 
-
-
-
> refactor: use join_all in event looping

- crates/core/src/client/helpers.rs
- crates/core/src/client/mod.rs
- crates/core/src/mock/assert_helpers.rs
- crates/core/src/models/block.rs
- crates/core/src/models/felt.rs
> feat: replace safe_get_evm address

- crates/core/src/client/api.rs
- crates/core/src/client/constants.rs
- crates/core/src/client/helpers.rs
- crates/core/src/client/mod.rs
- crates/core/src/mock/wiremock_utils.rs
- crates/core/src/models/block.rs
- crates/eth-rpc/src/eth_rpc.rs
> feat: add block id wrapper

- .github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md
- .github/ISSUE_TEMPLATE/04_RPC_METHOD_REQUEST.md
> refactor: lighten and optimize issue template

- .github/PULL_REQUEST_TEMPLATE.md
- crates/core/src/client/api.rs
- crates/core/src/client/errors.rs
- crates/core/src/client/mod.rs
- crates/core/src/client/tests/mod.rs
- crates/core/src/mock/wiremock_utils.rs
- crates/core/src/models/block.rs
- crates/core/src/models/convertible.rs
- crates/core/src/models/event.rs
- crates/core/src/models/transaction.rs
- crates/core/tests/client.rs
- crates/eth-rpc/src/eth_rpc.rs
- crates/eth-rpc/src/lib.rs
- crates/eth-rpc/src/main.rs
- crates/eth-rpc/tests/utils.rs
Resolves: #256 
Made Provider in all the crates logic generic
> refactor: make provider trait generic in the whole repo

- crates/core/src/client/mod.rs
- crates/core/src/client/tests/mod.rs
Fix underflow and conversions errors in fee history.
Resolves: #232 
The fee history function is tested, conversion and underflow errors are fixed.
> fix: fee history

- Makefile
- foundry.toml
Added default value for `forge` in the `foundry.toml`:
- `legacy = true` because no fee market on starknet
- default RPC to kakarot-rpc localhost
> Foundry config

- .env.example
- Makefile
- crates/core/src/client/config.rs
- crates/core/src/client/constants.rs
- crates/core/src/client/errors.rs
- crates/core/src/client/mod.rs
- crates/core/src/client/tests/mod.rs
- crates/core/src/kakarot/mod.rs
- crates/core/src/mock/wiremock_utils.rs
- crates/core/tests/client.rs
- crates/eth-rpc/src/main.rs
- crates/eth-rpc/tests/utils.rs
Time spent on this PR: 1day
Resolves: #273 
> feat: add possibility to have sequencer provider or jsonrpc provider

- Makefile
> DevX Makefile bis

- Cargo.lock
- crates/eth-rpc/Cargo.toml
- crates/eth-rpc/src/lib.rs
Allow all origins, methods and headers in the RPC
> Allow all origin, headers and methods in RPC

- crates/core/src/client/api.rs
- crates/core/src/client/constants.rs
- crates/core/src/client/helpers.rs
- crates/core/src/client/mod.rs
- crates/core/src/client/tests/mod.rs
- crates/core/src/mock/constants.rs
- crates/core/src/models/call.rs
Adds the gas price endpoint.
Resolves: #171 
Gas price route is implemented and tested.
> feat: gas price

- .github/workflows/kakarot_rpc.yml
- Dockerfile
- crates/core/src/client/config.rs
- crates/eth-rpc/src/main.rs
Kindly see https://github.com/keep-starknet-strange/madara-infra/issues/7 for context. This pr does the following:
- add sharingan as a network for the RPC
- update supported platforms for binaries
> feat: add sharingan for starknet stack

- Makefile
Updates the git submodule to the latest commit of Kakarot + fixes error in the Makefile.
Resolves: #NA
Submodule points to latest commit of Kakarot and Makefile works as intended.
> fix: update kakarot commit + fix makefile

- Makefile
- crates/core/src/client/mod.rs
Fixes the estimate fee problem causing metamask to not be able to proceed with gas estimation.
Resolves: #NA
MM can now correctly estimate the fee. Also fixes the Makefile in order to always include the .env.
> feat: update estimated fee

- crates/core/src/client/constants.rs
- crates/core/src/client/mod.rs
Set a minimum gas fee when calling estimate_gas endpoint.
Resolves: #NA
Estimate fee works on MM even if actual estimation is under 21,000 gas.
> fix: update min gas fee

- .github/workflows/kakarot_rpc.yml
Time spent on this PR: 0
Resolves: #335 
Parallelize building of images for different platforms using matrix
> feat: parallelize docker build and push

- Cargo.lock
- Cargo.toml
- crates/core/tests/utils/deploy_helpers.rs
Following Reth (see [this commit](https://github.com/paradigmxyz/reth/commit/af604289bb7f7f6da08926a071cc18d285d32247)) we need to remove
their `ruint` patch.
> Remove ruint patch

- crates/core/src/contracts/tests/mod.rs
> fix: fix import error in balance tests

- Cargo.lock
- crates/conformance-test-utils/src/madara.rs
- crates/conformance-test-utils/src/types.rs
Time spent on this PR: 0.2
Resolves: #382 
We are able to set the storage data for prefunding an address in Madara
> feat: add utility function to pre-fund starknet address in Madara

- Cargo.lock
- crates/core/src/test_utils/deploy_helpers.rs
- crates/eth-rpc/Cargo.toml
- crates/eth-rpc/src/lib.rs
- crates/eth-rpc/src/test_utils.rs
- crates/eth-rpc/tests/integration.rs
- crates/eth-rpc/tests/rpc.rs
- crates/eth-rpc/tests/utils.rs
Time spent on this PR: 0.5
Resolves: #365 
- Add integration test environment for Kakarot RPC with the following
- TestSequencer
- Deployed Kakarot contracts
- Kakarot RPC server
- Move `test_utils` so it can be used in other crates
> dev: add integration test environment for `eth-rpc`

- Cargo.lock
- Cargo.toml
- crates/conformance-test-utils/src/kakarot.rs
- crates/conformance-test-utils/src/madara.rs
- crates/core/src/client/api.rs
- crates/core/src/client/mod.rs
- crates/core/src/contracts/contract_account.rs
- crates/core/src/contracts/tests/mod.rs
- crates/core/src/test_utils/deploy_helpers.rs
- crates/core/tests/client.rs
- crates/eth-rpc/src/test_utils.rs
Introduce a `KakarotTestEnvironment` structure that is used to initialize a test environment using Kakarot deployed on a test sequencer.
Resolves: #376 
Removes the test boiler plate code using `KakarotTestEnvironment`.
> fix: clean deploy helpers

- Cargo.lock
- crates/conformance-test-utils/src/madara.rs
Time spent on this PR: 0.5
Resolves: #379 
- We are now able to set the storage of a Kakarot contract account
- Refactor code to it more DRY
- This is a continuation of #383
> feat: modify genesis set storage contract account

- .github/workflows/benchmark.yml
- .gitmodules
- .prettierignore
- .prettierrc.json
- benchmarking/.gitignore
- benchmarking/README.md
- benchmarking/package-lock.json
- benchmarking/package.json
- benchmarking/scripts/benchmark.sh
- benchmarking/scripts/check_rpc_is_init.js
- benchmarking/scripts/deploy_kakarot.sh
- benchmarking/scripts/metrics.js
- benchmarking/scripts/native-token-transfer.yml
- benchmarking/scripts/processor.js
- benchmarking/scripts/run_rpc.sh
- benchmarking/scripts/utils.js
This PR is part of the epic #322 , and resolves the issue with #374.
The PR does the following:
- Adds a `benchmarking` directory which is self-sufficient for benchmarking Kakarot on Madara
- Adds Madara as a submodule, the build of which is used at the time of benchmarking
- Adds `benchmarking.yml` to the github workflows, so that we can do these benchmarking at github actions
- The workflow run on each pull request and pr to main
-  It will compare the performance of commits from new PR with the previous historical data
- Once a PR is merged, it will automatically create a website on the branch gh:pages to host these benchmarks via GitHub pages, if it has already created this website then it will update the data for the website.
- `README.md` of `benchmarking` directory has all …
> feat: add native token transfer benchmarks

- crates/core/src/client/mod.rs
- crates/core/src/contracts/account.rs
Resolves: #392 
We only need to handle `ContractNotFound` for non existing contracts
> dev: remove `ContractError` match

- .github/workflows/kakarot_rpc.yml
Resolves: #411 
Fix build in ci and able to build images both for arm and amd
> dev: add large runners

- CHANGELOG.md
- Cargo.lock
- Makefile
- crates/conformance-test-utils/src/kakarot.rs
- crates/conformance-test-utils/src/madara/utils.rs
- crates/core/src/contracts/account.rs
- crates/core/src/contracts/contract_account.rs
- crates/core/src/test_utils/constants.rs
- crates/core/src/test_utils/deploy_helpers.rs
- crates/core/src/test_utils/fixtures.rs
- crates/core/tests/client.rs
- crates/eth-rpc/Cargo.toml
- crates/eth-rpc/src/test_utils.rs
- crates/eth-rpc/tests/integration.rs
Updates all tests to use the generated Katana dump.
Resolves: #415 
Test are fast now!
> test: update tests to use katana dump

- .github/workflows/changelog.yml
smol pr to solve cumbersome adding label by hand
> fix: add dependencies as skip-label to not fail dependabot CI job

- .github/workflows/kakarot_rpc.yml
- CHANGELOG.md
- Cargo.lock
- Dockerfile
- crates/eth-rpc/Cargo.toml
- docker-compose.katana.yaml
Time spent on this PR: 0.2
Resolves: #425 
Cross-compile the binaries and improve build time [57 m](https://github.com/alamatxyz/kakarot-rpc/actions/runs/5833654529/job/15821695313) &rarr; [12 m](https://github.com/alamatxyz/kakarot-rpc/actions/runs/5869304788/job/15914007439)
> dev: cross compile binaries to speed up build time

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/conformance-test-utils/Cargo.toml
- crates/conformance-test-utils/src/hive/genesis.rs
- crates/conformance-test-utils/src/types.rs
Remove Madara as a dependency of the repo.
Resolves: #NA
Madara is no longer a dependency of the conformance-test-utils crate.
> fix: remove madara as dep

- CHANGELOG.md
- crates/core/src/client/api.rs
- crates/core/src/client/mod.rs
- crates/core/src/client/tests/mod.rs
- crates/core/tests/client.rs
- crates/eth-rpc/src/api/eth_api.rs
- crates/eth-rpc/src/servers/eth_rpc.rs
Time spent on this PR: 3
Resolves: #440 
> dev: update return type for get_logs method

- .github/workflows/test.yml
- Makefile
Adds nextest for all rust related tests in order to shorten the test length.
Resolves: #437 
Runs CI faster using nextest.
> ci: add nextest in CI

- CHANGELOG.md
- crates/hive-utils/src/hive/genesis.rs
- crates/hive-utils/src/madara/utils.rs
- crates/hive-utils/src/test_data/madara_genesis.json
Add the missing storage variables to the Madara genesis as listed in the issue.
Resolves: #447 
Adds missing storage variables (see issue) to the Madara genesis.
> fix: hive storage

- Dockerfile
Time spent on this PR: 0.3
Resolves: #472 
Images successfully built [here](https://github.com/alamatxyz/kakarot-rpc/actions/runs/5949961372)
> dev: add sysroot

- crates/hive-utils/Dockerfile
Time spent on this PR: 0
Resolves: #481 
Reduce logging so blocks don't stop from propagating and solves the timeout issue in hive tests
> dev: reduce logging

- crates/core/src/test_utils/bin/dump-katana.rs
Reverts kkrt-labs/kakarot-rpc#503
> Revert "fix: update the dump katana script"

- crates/core/src/test_utils/bin/dump-katana.rs
Quick renaming and removing useless fields in the submodules.json.
Resolves: #NA
Saving kakarot sha to normal file iso json
> fix: update naming in dump

- Cargo.lock
- Cargo.toml
- Makefile
- crates/core/src/client/api.rs
- crates/core/src/client/constants.rs
- crates/core/src/client/mod.rs
- crates/core/src/contracts/erc20/ethereum_erc20.rs
- crates/core/src/contracts/kakarot.rs
- crates/core/src/contracts/tests/mod.rs
- crates/core/tests/client.rs
- crates/eth-rpc/src/servers/eth_rpc.rs
> feat: update kakarot API

- Makefile
Time spent on this PR: 0.1day
Resolves: #517 
> chore: switch from docker-compose to docker compose

- crates/core/src/test_utils/deploy_helpers.rs
Resolves: https://github.com/kkrt-labs/ef-tests/issues/70
The total max steps for the test sequencer has been increase so that the ef-tests don't fail because they run out of resources.
> feat: increase max step limits for test sequencer

- crates/eth-rpc/src/api/net_api.rs
- crates/eth-rpc/src/rpc.rs
- crates/eth-rpc/src/servers/net_rpc.rs
- crates/eth-rpc/tests/integration.rs
Time spent on this PR: 3 hours
#641 
This PR exposes a health check through Net API o check that the RPC URL is currently online.
I also added missing comments for block_number function in net_api.rs file.
> FEAT: add healthCheck to KKRT Net API

- .trunk/trunk.yaml
- src/hive_utils/hive_genesis.rs
- tests/hive_utils.rs
Resolves: #NA
The Kakarot submodule is bumped to the latest commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/685)
> dev: bump kakarot

- Cargo.toml
- Makefile
- docker-compose.yaml
- src/eth_rpc/servers/eth_rpc.rs
- src/models/transaction_receipt.rs
Resolves: #NA
The docker compose correctly starts all the various services to provide a node (Madara) with Kakarot deployed on it along with the custom kakarot rpc layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/690)
> fix: docker compose

- docker-compose.yaml
Time spent on this PR: NA
Resolves: #NA
Pin Madara image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/700)
> fix: pin madara image to 0.6.0

- .trunk/trunk.yaml
- src/models/transaction_receipt.rs
Resolves: #695 
Replace events parsing with a call to `create_address` from reth_primitives.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/701)
> feat: clean to_eth_transaction_receipt

- .github/workflows/kakarot_rpc.yml
- .github/workflows/pull_request.yml
Resolves: #NA
Fixes the pushing of the binaries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/702)
> fix: pushing of binaries

- .trunk/trunk.yaml
- Cargo.lock
- src/eth_rpc/servers/alchemy_rpc.rs
- src/models/event.rs
- src/models/event_filter.rs
- src/models/felt.rs
- src/models/signature.rs
- src/models/transaction/transaction_signed.rs
- src/models/transaction_receipt.rs
- src/starknet_client/mod.rs
- tests/test_data/conversion/starknet/event_filter_without_address.json
Resolves: #705
Fixes an issue in the filtering of events, cleans some redundant code and adds debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/713)
> feat: improve logging

- src/contracts/erc20.rs
- src/starknet_client/mod.rs
Resolves: #721 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/723)
> feat: bump kakarot

- src/contracts/erc20.rs
- src/eth_rpc/servers/eth_rpc.rs
- src/models/block.rs
- src/models/errors.rs
- src/models/event.rs
- src/models/transaction/transaction.rs
- src/models/transaction/transaction_signed.rs
- src/models/transaction_receipt.rs
- src/starknet_client/mod.rs
- tests/starknet_client.rs
- tests/test_utils/constants.rs
- tests/test_utils/eoa.rs
Resolves: #NA
Additional cleaning of the code + optimistic implementation of compute_starknet_address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/714)
> dev: cleaning

- docker/rpc/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/736)
> feat: fix docker image

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- rust-toolchain
- src/config.rs
- src/eth_provider/contracts/erc20.rs
- src/eth_provider/database/types/serde/mod.rs
- src/eth_provider/database/types/transaction.rs
- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/eth_rpc/api/eth_api.rs
- src/eth_rpc/api/web3_api.rs
- src/eth_rpc/mod.rs
- src/eth_rpc/rpc.rs
- src/eth_rpc/servers/eth_rpc.rs
- src/eth_rpc/servers/web3_rpc.rs
- src/models/felt.rs
- src/test_utils/eoa.rs
- src/test_utils/evm_contract.rs
- src/test_utils/mongo/mod.rs
- src/test_utils/sequencer/mod.rs
- tests/alchemy.rs
- tests/eth_provider.rs
Resolves: #735 and #733 
Bump jsonrpsee and reth.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/747)
> dev: bump deps

- .github/workflows/kakarot_rpc.yml
- .github/workflows/test.yml
- docker-compose.yaml
- docker/rpc/Dockerfile
- src/eth_provider/starknet/kakarot_core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/751)
> ci: add on release trigger for docker image

- .github/workflows/kakarot_rpc.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/758)
> fix: fix build arg

- src/eth_provider/provider.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/759)
> chore: bump kakarot

- src/bin/hive_genesis.rs
- src/bin/katana_genesis.rs
- src/test_utils/katana/genesis.rs
Resolves: #NA
Reorgs the generation of the genesis, add par iter for class loading and moves `KatanaManifest`.
> fix: update genesis

- docker/rpc/Dockerfile
Resolves: #NA
Push the hive genesis binary in the rpc image.
> dev: update docker

- Makefile
- src/eth_provider/constant.rs
- src/eth_provider/contracts/erc20.rs
- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
- src/eth_rpc/servers/eth_rpc.rs
> feat: add basefee as kakarot storage slot

- .trunk/trunk.yaml
- .vscode/settings.json
- Cargo.toml
- Makefile
- docker/rpc/Dockerfile
- src/bin/hive_genesis.rs
- src/bin/katana_genesis.rs
- src/eth_provider/constant.rs
- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/test_utils/eoa.rs
- src/test_utils/hive/mod.rs
- src/test_utils/katana/genesis.rs
- tests/eth_provider.rs
- Updates the docker file in order to generate the binaries for the hive test.
- Fixes hive genesis issues.
- Adds rpc deployment of EOA if running with "hive" feature.
> feat: update docker and genesis

- .trunk/trunk.yaml
- docker/rpc/Dockerfile
- src/bin/hive_genesis.rs
- src/bin/katana_genesis.rs
- src/eth_provider/constant.rs
- src/eth_provider/provider.rs
- src/main.rs
- src/test_utils/eoa.rs
- src/test_utils/katana/genesis.rs
- src/test_utils/katana/mod.rs
- tests/eth_provider.rs
Resolves: #NA
Copies the hive binary from the builder.
> fix: copy hive binary + automatic deployment

- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
- tests/eth_provider.rs
Resolves: #786
Fixes `get_code` when calling contract that isn't deployed.
> fix: hive test `ContractDeploymentOutOfGas`

- src/eth_provider/provider.rs
- src/eth_rpc/api/eth_api.rs
- src/eth_rpc/servers/eth_rpc.rs
- tests/eth_provider.rs
> fix storage at type

- docker/hive/Dockerfile
> chore bump rpc tag in hive dockerfile

- .trunk/trunk.yaml
- docker/rpc/Dockerfile
Resolves: #NA
Fixes the image issue on the RPC for incompatible libc versions.
> fix: upgrade debian image

- docker/hive/Dockerfile
> bump rpc tag in hive dockerfile

- src/eth_rpc/api/eth_api.rs
- src/eth_rpc/servers/eth_rpc.rs
> add blob base fee

- .trunk/trunk.yaml
- Cargo.lock
- Cargo.toml
- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
- src/models/felt.rs
Resolves: #NA
Light cleaning of various APIs.
> fix: light cleaning

- src/eth_provider/provider.rs
- src/models/block.rs
> set conversion of blocktag latest to sn pending

- src/eth_provider/constant.rs
- src/eth_provider/provider.rs
- src/test_utils/mongo/mod.rs
Resolves: #824 
Empty withdrawals are added to the Block. Invariant also added to check the withdrawal_root is always the empty hash.
> fix: add withdrawals

- .github/workflows/kakarot_rpc.yml
- .github/workflows/test.yml
- .gitignore
- docker/hive/Dockerfile
- docker/rpc/Dockerfile
- scripts/extract_abi.sh
- src/eth_provider/starknet/kakarot_core.rs
- src/eth_provider/starknet/mod.rs
>  add hive in CI

- .github/workflows/kakarot_rpc.yml
> fix release workflow

- docker/hive/Dockerfile
- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
- src/eth_rpc/api/eth_api.rs
- src/eth_rpc/servers/eth_rpc.rs
- tests/eth_provider.rs
Resolves: #822
Fixes the types used in the RPC in order to match Reth.
> fix: rpc types

- .vscode/settings.json
- Cargo.toml
- docker/hive/Dockerfile
- src/eth_provider/provider.rs
Resolves: #831 
Fix the transaction index issue.
> fix: remove hive chain feature + fix index

- .github/workflows/test.yml
Resolves: #828
Add the rpc-compat test (only the currently passing ones) to the CI.
> feat: add rpc-compat tests

- .github/workflows/test.yml
Time spent on this PR: 0.4 day
Resolves: #NA
Add 4 hive tests.
> feat: add 4 hive tests

- .trunk/trunk.yaml
- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
Resolves: #NA
Clean part of the code and improve performances by using `with_capacity` instead of `Vec::new()`.
> dev: improve perfs

- .github/workflows/test.yml
- src/eth_provider/provider.rs
Resolves: #NA
Fix a bug in block_receipts and add more passing hive tests.
> fix: add more tests and fix `block_receipts`

- .github/workflows/kakarot_rpc.yml
- docker-compose.sepolia.yaml
- docker-compose.yaml
- docker/hive/Dockerfile
- src/bin/hive_chain.rs
- src/eth_provider/constant.rs
- src/eth_provider/provider.rs
- src/test_utils/eoa.rs
- src/test_utils/evm_contract.rs
- src/test_utils/katana/genesis.rs
> chore bump kakarot

- docker-compose.sepolia.yaml
- src/eth_provider/provider.rs
> name call request gas limit

- .github/workflows/kakarot_rpc.yml
> bump timeout of release job

- src/eth_provider/provider.rs
- src/test_utils/mongo/mod.rs
- tests/eth_provider.rs
> pending block number transformed into tag

- .github/workflows/kakarot_rpc.yml
Resolves: #NA
Fix an issue in the release CI.
> fix issue in release of CI

- src/bin/hive_chain.rs
- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
> add tracing and fix sepolia bug

- .github/workflows/kakarot_rpc.yml
- .github/workflows/spell_check.yml
- .github/workflows/test.yml
- .trunk/trunk.yaml
- Cargo.lock
- Cargo.toml
- Makefile
- rust-toolchain
- src/eth_rpc/servers/eth_rpc.rs
- src/test_utils/hive/mod.rs
Time spent on this PR: 2 day
Resolves: partially solves 863
Bumps the Katana dep to `v0.6.0-alpha.6`.
> dev: bump katana

- src/test_utils/hive/mod.rs
Resolves: #NA
Improve perf for maps + use `entry` API.
> dev: small fix

- .github/workflows/kakarot_rpc.yml
> ci: multi docker image arch

- .github/workflows/test.yml
- docker/hive/Dockerfile
- src/eth_provider/provider.rs
- src/test_utils/hive/mod.rs
- tests/eth_provider.rs
Resolves: partially resolves 871
Add 2 hive passing tests.
> fix: couple of hive errors

- .github/workflows/test.yml
Resolves: #NA
Add `debug_getRawTransaction` to the hive CI.
> add `debug_getRawTransaction` hive

- README.md
- src/eth_provider/provider.rs
Resolves: #871 
- Adds details about all skipped hive tests in the README + details about the skipped fields for passing tests.
- Boy scout commit to simplify `fee history`.
> dev: hive readme

- docker/rpc/Dockerfile
- docker/rpc/Dockerfile.cross
Resolves: #NA
Fixes the `[FATAL tini (7)] exec /usr/local/bin/kakarot-rpc failed: Permission denied` error on the docker compose.
> fix: add execute permission

- .trunk/trunk.yaml
- docker/rpc/Dockerfile
- docker/rpc/Dockerfile.cross
Resolves: #NA
Fix the docker image.
> fix docker

- .github/workflows/push.yml
- docker-compose.yaml
- docker/rpc/Dockerfile.cross
Resolves: #NA
Fix the error in the compose.
> fix: compose

- src/eth_provider/error.rs
- src/eth_rpc/servers/debug_rpc.rs
- src/models/block.rs
- src/models/felt.rs
- src/models/mod.rs
- src/models/transaction.rs
- tests/debug_api.rs
Draft PR until I implement tests
Resolves: #522 
> feat: add debug_getRawBlock

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/bin/hive_genesis.rs
- src/bin/katana_genesis.rs
- src/eth_provider/starknet/kakarot_core.rs
- src/main.rs
- src/test_utils/katana/mod.rs
Resolves: #892
- Adds hive to the CI for `debug raw block`.
-Remove dotenv in favour our dotenvy.
> test: debug raw block

- .trunk/trunk.yaml
- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/eth_rpc/servers/debug_rpc.rs
- tests/debug_api.rs
Resolves: #890
Adds debug raw transactions.
> feat: add raw transactions endpoint

- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/eth_rpc/servers/debug_rpc.rs
- src/models/block.rs
- src/test_utils/mongo/mod.rs
- tests/debug_api.rs
Time spent on this PR: 1h30
Resolves: #523 
- Implementation and testing of `debug_getRawHeader` endpoint
- Decoupling of the already existing `rpc_to_primitive_header` method to be able to transform the rpc header into a primitive header correctly.
> Implement `debug_getRawHeader`

- Makefile
This pull request fixes the issue of encountering cannot stat 'build/ssj/contracts_Precompiles.contract_class.json': No such file or directory when running setup.
```
- IUniswapV2Callee.0.8.24
- IUniswapV2ERC20.0.8.24
- IUniswapV2Factory.0.8.24
- IUniswapV2Pair.0.8.24
- PlainOpcodesTest
make[1]: Leaving directory '/mnt/ssd3/opensource/kakarot-rpc/lib/kakarot'
mv: cannot stat 'build/ssj/contracts_Precompiles.contract_class.json': No such file or directory
make: *** [Makefile:15: setup] Error 1
```
Time spent on this PR: half hour
Resolves: #905
```
make[1]: Leaving directory '/mnt/ssd3/opensource/kakarot-rpc/lib/kakarot'
./scripts/extract_abi.sh
Starting build process
Removing existing build directory ./.kakarot
Creating new build …
```
> dev: fix contracts_Precompiles not found bug

- .github/workflows/kakarot_rpc.yml
- .github/workflows/test.yml
- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/models/block.rs
- src/models/felt.rs
- src/models/mod.rs
- src/models/transaction.rs
Time spent on this PR: 30 min
Resolves: #902
- A primitive variant is added to `EthereumDataFormatError` in order to replace the old `ConversionError` item
> Add primitive variant for `EthereumDataFormatError`

- src/bin/hive_chain.rs
- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
Resolves: #NA
Clean the layout of the `send_raw_transaction` in order to make it more readable.
> dev: clean send_raw_transaction

- src/eth_provider/error.rs
- src/eth_provider/provider.rs
Resolves: #NA
Error message display is correct.
> fix: error display

- Cargo.lock
- Makefile
- README.md
Fix kakarot deploy script path.
> Fix kakarot deploy script path

- Cargo.lock
- Cargo.toml
- src/eth_rpc/middleware/metrics.rs
Resolves: #NA
Remove the dep on `pin-project` and replace with `pin-project-lite` for a lighter dep.
> dev: lighten deps with pin-project-lite

- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
Resolves: #NA
Use `estimate_gas` instead of `eth_call` endpoint for gas estimation.
> feat: update to estimate-gas endpoint

- docker-compose.prod.yaml
> update kakarot testnet sepolia compose

- Cargo.lock
- Cargo.toml
- src/eth_provider/database/types/receipt.rs
- src/eth_provider/database/types/transaction.rs
- src/eth_provider/starknet/kakarot_core.rs
- src/eth_rpc/servers/debug_rpc.rs
- src/models/block.rs
- src/models/felt.rs
- src/models/transaction.rs
- src/test_utils/mongo/mod.rs
- tests/debug_api.rs
Resolves: #889
Bump reth version to v0.2.0-beta.5
> Bump reth version to v0.2.0-beta.5

- README.md
- indexer/src/types/header.ts
Resolves: #949 
Avoid the Kakarot.call to defaut to "pending' block.
> fix(indexer): block identifier error

- README.md
Update build-arg hive commands
> update build-arg hive commands

- src/eth_provider/constant.rs
- src/models/block.rs
- tests/eth_provider.rs
Use random values in provider tests.
> Use random values in provider tests

- src/models/block.rs
Time spent on this PR: 5 min
Small refactoring for `rpc_to_primitive_block`.
> Small refactoring for `rpc_to_primitive_block`

- Cargo.lock
- Cargo.toml
Some crate updates in `Cargo.toml`
> Some crate updates

- src/eth_provider/provider.rs
- src/test_utils/katana/mod.rs
- tests/eth_provider.rs
Time spent on this PR: 30 min
- Randomize unit test `test_block_by_hash`
- Small refactoring
> randomize `test_block_by_hash`

- src/eth_provider/provider.rs
- src/eth_rpc/mod.rs
- src/eth_rpc/rpc.rs
- src/models/block.rs
> Small refactor

- .github/workflows/kakarot_rpc.yml
- .github/workflows/test.yml
- docker/hive/Dockerfile
Time spent on this PR: 30 min
Resolves: #746
Fix `GITHUB_TOKEN` in hive.
> fix `GITHUB_TOKEN` in hive

- Cargo.lock
- Cargo.toml
> Bump `ef-testing`

- docker-compose.prod.yaml
- docker-compose.staging.yaml
smol PR: rename_volumes_to_avoid_clash of names and bugs locally
> feat: rename_volumes_to_avoid_clash

- src/eth_provider/provider.rs
In order for a less verbose implementation:
- `into()` is used to transform a `B256` into a hash variant of `BlockHashOrNumber::Hash`
- `into()` is used to transform a `u64` into a hash variant of `BlockHashOrNumber::Number`
> Use `into()` to get `BlockHashOrNumber`

- src/test_utils/katana/genesis.rs
Time spent on this PR: 15 min
Simplify `collect` when possible.
> Simplify `collect` when possible

- src/eth_provider/provider.rs
Time spent on this PR: 5 min
Use `into()` to transform `U64` to `BlockHashOrNumber`.
> Use `into()` to transform `U64` to `BlockHashOrNumber`

- Cargo.lock
- Cargo.toml
- src/eth_provider/contracts/erc20.rs
- src/eth_provider/database/types/header.rs
- src/eth_provider/database/types/receipt.rs
- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/eth_rpc/servers/debug_rpc.rs
- src/models/block.rs
- src/models/felt.rs
- src/models/transaction.rs
- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- src/tracing/mod.rs
- tests/tests/debug_api.rs
- tests/tests/eth_provider.rs
- tests/tests/trace_api.rs
Time spent on this PR: 2h
Bump `reth`to `v0.2.0 beta.6`
> Bump `reth` to `v0.2.0 beta.6`

- src/eth_provider/provider.rs
Small refactoring around `FilterChanges`
> Small refactoring around `FilterChanges`

- docker-compose.prod.yaml
Bump Kakarot address for local running of the production environment
> bump kakarot address and class hashes

- docker-compose.yaml
> Use latest kakarot deployer image in docker compose

- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/eth_rpc/servers/debug_rpc.rs
- src/models/block.rs
- tests/tests/debug_api.rs
Time spent on this PR: 1hr (I'm relatively new to rust)
Resolves: #970 
> refactor: Use `reth` `try_from` impl to convert blocks and headers

- src/eth_provider/provider.rs
- if nonce of sn protocol isnt found, return 0 nonce
> fix protocol nonce not found

- src/eth_provider/provider.rs
- src/eth_rpc/servers/alchemy_rpc.rs
> Small refactor in provider

- .gitignore
- Cargo.lock
- Cargo.toml
- proptest-regressions/eth_provider/utils.txt
- src/eth_provider/utils.rs
> Add proptest for `split_u256`

- src/eth_provider/provider.rs
Time spent on this PR: 0.1day
- Fix max fee computation, we're currently taking the whole balance as a max fee of the user and it might break on testnet.
> don't take 100% of balance

- src/test_utils/rpc/mod.rs
- tests/tests/alchemy_api.rs
- tests/tests/debug_api.rs
- tests/tests/trace_api.rs
> Add `RawRpcParamsBuilder` as a test util

- Makefile
- docker-compose.yaml
- docker/hive/Dockerfile
> bump kakarot to 0.7.4

- src/config.rs
> refactor in config file

- Makefile
Adding usages for the makefile
Time spent on this PR: 10 minutes
Resolves: #1031 
- [ X] Feature
> Makefile usages

- .trunk/trunk.yaml
- Cargo.lock
- Cargo.toml
- Makefile
- src/test_utils/eoa.rs
- src/test_utils/evm_contract.rs
- src/test_utils/fixtures.rs
- src/tracing/config.rs
- tests/tests/trace_api.rs
Time spent on this PR: 3 days
Resolves: #1012 
Adds tracing for EIP 3074.
> feat: tracing eip3074

- src/eth_provider/error.rs
> Small refactor for eth_provider error

- src/tracing/mod.rs
Resolves: #1047 
Use the tracing's environment to set the base fee of a traced transaction to the base fee of the block
> fix: set base fee of transaction to the block's basefee

- src/eth_provider/constant.rs
- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- tests/tests/eth_provider.rs
Time spent on this PR: 1 hour
Resolves: #1048 
Same functional behaviour
> fix: Add comments to constants and rename + small refactor

- .trunk/trunk.yaml
- src/eth_provider/provider.rs
Time spent on this PR: 20 minutes
Resolves: #1052 
> increased gas by 20%

- docker/indexer/Dockerfile
Resolves: #NA
Fixes the indexer docker file.
> fix: indexer docker

- src/test_utils/katana/genesis.rs
> derive `Default` for `KatanaGenesisBuilder`

- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
> remove `try_from_u8_iterator`

- src/eth_rpc/servers/debug_rpc.rs
- src/models/block.rs
- src/models/transaction.rs
- tests/tests/debug_api.rs
- tests/tests/trace_api.rs
Time spent on this PR: 1h30
Resolves: #960 
Use TryFrom trait of reth for conversion from rpc transaction to primitive transaction
> feat: Remove rpc_to_primitive_transaction to use reth TryFrom trait

- tests/tests/trace_api.rs
> refactor in header helper construction

- src/tracing/mod.rs
Time spent on this PR: 10 minutes
Resolves: #1058 
Normal
> from refactor to transactionInfo

- .trunk/trunk.yaml
- src/eth_provider/database/types/log.rs
- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- tests/tests/eth_provider.rs
Resolves: #NA
Fixes the filtering on logs in the mongo.
> fix: get logs

- .trunk/trunk.yaml
- src/eth_provider/error.rs
- src/eth_rpc/api/debug_api.rs
- src/eth_rpc/servers/debug_rpc.rs
- src/eth_rpc/servers/trace_rpc.rs
- src/tracing/builder.rs
- src/tracing/config.rs
- src/tracing/mod.rs
- tests/tests/trace_api.rs
Resolves: #1079
Implement the `debug_traceTransaction` endpoint for the RPC.
> feat: debug transaction

- src/eth_rpc/servers/eth_rpc.rs
Resolves: #NA
Removes some of the fields in the `tracing` macro in order to reduce excessive logging.
> dev: remove excessive logging

- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/eth_rpc/api/mod.rs
- src/eth_rpc/api/txpool_api.rs
- src/eth_rpc/rpc.rs
- src/eth_rpc/servers/mod.rs
- src/eth_rpc/servers/txpool_rpc.rs
- src/test_utils/katana/mod.rs
- tests/tests/mod.rs
- tests/tests/txpool_api.rs
> add `txpool_content` and `txpool_content_from`

- Cargo.toml
- src/config.rs
- src/eth_provider/error.rs
- src/eth_rpc/middleware/metrics.rs
- src/test_utils/mongo/mod.rs
> Add `use_self` clippy lint

- src/tracing/builder.rs
Resolves: #NA
Fixes the tracing by setting a huge gas limit.
> fix: tracing

- docker-compose.prod.yaml
Redeployed Kakarot to Kakarot Sepolia
Linked to https://github.com/kkrt-labs/kakarot/commit/099b58192e489494f7dd779711b08feeb40c239c
> redeploy kakarot

- Cargo.toml
- src/eth_provider/database/mod.rs
- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/eth_rpc/middleware/metrics.rs
- src/models/transaction.rs
- src/test_utils/evm_contract.rs
- src/test_utils/katana/genesis.rs
- src/test_utils/mongo/mod.rs
- src/test_utils/rpc/mod.rs
> Add warn on `missing_const_for_fn` clippy

- src/eth_rpc/api/txpool_api.rs
- src/eth_rpc/servers/txpool_rpc.rs
- tests/tests/txpool_api.rs
> add `txpool_status`

- crates/sequencer/Cargo.lock
- crates/sequencer/Cargo.toml
- crates/sequencer/src/mempool/Cargo.toml
- crates/sequencer/src/mempool/src/lib.rs
- crates/sequencer/src/mempool/src/validate/mod.rs
Resolves: #NA
Add a transactino validator builder wrapper which forces the Validator to refuse EIP4844 transactions.
> feat: reject eip 4844

- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/eth_rpc/api/txpool_api.rs
- src/eth_rpc/servers/txpool_rpc.rs
- tests/tests/txpool_api.rs
> add `txpool_inspect`

- Cargo.toml
- docker-compose.yaml
> fix deployer tag

- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
Resolves: #1074 
Clean the `to_logs_filter function`.
> dev: clean `to_logs_filter`

- .github/workflows/test.yml
- indexer/src/main.ts
- indexer/src/utils/filter.test.ts
- indexer/src/utils/filter.ts
Resolves: #1113 
Skips transactions which fail ethereum validation. Also adds deno test to the CI.
> fix: indexer validation

- src/test_utils/katana/genesis.rs
> use default pattern for `GenesisJson`

- .trunk/trunk.yaml
- Cargo.lock
- README.md
Resolves: #NA
Adds documentation about running our tests in the README.
> dev: readme

- src/eth_provider/provider.rs
> add logs for retry service

- Cargo.lock
- Cargo.toml
- src/eth_provider/error.rs
Resolves: #NA
Adds decoding of the `REVERT` opcode return data.
> feat: add solidity error decoding

- Cargo.toml
- src/main.rs
Resolves: #NA
Reduce the logs produced by the RPC to only log the `kakarot_rpc` crate logs.
> dev: reduce logs

- indexer/src/utils/filter.test.ts
Time spent on this PR: 5 hours
Resolves: #1117 
> isKakarotTransaction tests

- README.md
> Add guideline to run a node

- README.md
> update README table of content

- indexer/src/deps.ts
- indexer/src/main.ts
> enforce type on Apibara config

- src/tracing/mod.rs
Resolves: #NA
Some light refactoring in tracing.
> dev: refactor tracing

- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/tracing/builder.rs
- src/tracing/database.rs
- src/tracing/mod.rs
Time spent on this PR: 1:30
Resolves: #1112 
Adds explicit information in the Eth provider errors
> enh: eth provider errors

- src/eth_provider/provider.rs
> transform starknet tx to hex in log

- src/eth_rpc/servers/debug_rpc.rs
- src/eth_rpc/servers/trace_rpc.rs
- src/tracing/builder.rs
- src/tracing/mod.rs
> Reorganize tracing objects

- .trunk/trunk.yaml
- src/bin/hive_chain.rs
- src/eth_provider/constant.rs
- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
- src/tracing/mod.rs
- tests/tests/eth_provider.rs
> add retry in calldata

- .github/dependabot.yml
With https://github.com/kkrt-labs/kakarot/pull/1200, we don't need dependabot in RPC repo anymore.
> remove submodule dependabot

- .github/workflows/staging.yml
- .trunk/trunk.yaml
Resolves: #NA
Staging workflow can open a PR on Kakarot.
> test: staging

- .github/workflows/staging.yml
- scripts/staging.sh
Resolves: #NA
Unskip the precompiles run on staging.
> staging: add precompiles

- indexer/src/utils/hex.test.ts
> add more unit tests around padding utils

- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- tests/tests/eth_provider.rs
> fix block number to prevent failure on `get_logs` tests

- src/eth_provider/utils.rs
> simplify `to_logs_filter` using `FilterSet` `into_iter`

- .github/workflows/kakarot_release.yml
- .vscode/settings.json
- docker/indexer/Dockerfile
Resolves: #NA
The release workflow for the indexer should be fixed.
> fix: indexer release workflow

- src/tracing/builder.rs
> use `with_chain_id` for `CfgEnv`

- .github/workflows/staging.yml
- .trunk/trunk.yaml
- src/config.rs
Resolves: #NA
Add scarb in the staging in order to compile the cairo 1 contracts.
> staging: add scarb

- .github/workflows/kakarot_release.yml
Resolves: #NA
Apparently adding these tags makes it not compatible with the push-by-digest.
> fix: remove release tags

- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- tests/tests/eth_provider.rs
> add `get_logs` testing

- indexer/src/utils/filter.test.ts
- indexer/src/utils/filter.ts
> Clean up indexer filter functions and add test coverage

- indexer/src/types/transaction.test.ts
- indexer/src/types/transaction.ts
> support old/new calldata indexing

- src/eth_provider/provider.rs
> return 0 balance if native contract not found

- scripts/staging.sh
Resolves: #NA
Skip L1L2 messaging tests as these cannot be replicated on the staging.
> fix: skip l1 l2 messaging

- .trunk/trunk.yaml
- Cargo.lock
- Cargo.toml
- src/eth_rpc/servers/alchemy_rpc.rs
- src/lib.rs
- src/models/balance.rs
- src/test_utils/katana/mod.rs
- tests/tests/alchemy_api.rs
Resolves: #NA
Removes unused deps + refactors the `TokenBalanceFuture` implementation.
> dev: add `unused_crate_dependencies`

- src/config.rs
- src/eth_provider/constant.rs
- src/main.rs
Resolves: #570 
Removes the `Network` abstraction from the code base.
> dev: remove `Network`

- src/eth_provider/database/ethereum.rs
> Add unit tests for `EthereumTransactionStore`

- src/eth_provider/database/ethereum.rs
- src/eth_provider/database/mod.rs
- src/eth_provider/database/types/transaction.rs
> rm `StoredTransactionHash` and `transaction_hashes`

- src/eth_provider/database/types/transaction.rs
- src/test_utils/mongo/mod.rs
> move `mock_tx_with_type` to `StoredTransaction` file

- src/eth_provider/provider.rs
- src/eth_provider/utils.rs
Resolves: #1263 
Fixes the error when querying the eth balance on early blocks.
> fix(rpc/eth_getBalance): class hash not found 

- docker-compose.yaml
> chore: bump kakarot docker image

- src/eth_provider/database/ethereum.rs
- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/models/transaction.rs
- src/test_utils/eoa.rs
- src/test_utils/evm_contract.rs
- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- tests/tests/eth_provider.rs
Resolves: #1264 
Add validation of the transaction's gas limit, max priority fee and max fee.
> feat(rpc): extra validation send_raw_transaction

- .gitignore
- .katana/messaging_config.json
- docker-compose.yaml
> dev: add l1 rpc to local-rpc docker

- README.md
This PR adds `poetry` to the installation requirement in the README file.
Resolves: #1256
N/A
> Adding  installation requirement

- indexer/src/types/log.test.ts
- indexer/src/types/log.ts
> test(indexer): add more unit tests for log methods

- .gitignore
- Makefile
- src/retry/mod.rs
- src/tracing/mod.rs
Resolves: #NA
Updates the gitignore and refactors some function naming.
> dev(rpc): cleaning

- .trunk/trunk.yaml
- scripts/upgrade.sh
Resolves: #NA
Adds more details in the upgrade script.
> fix: update upgrade.sh

- Cargo.lock
- Cargo.toml
- docker-compose.prod.yaml
- docker-compose.yaml
Resolves: #NA
Update docker tags and crate version.
> dev(rpc): update tags

- Cargo.lock
- Cargo.toml
- Makefile
- docker-compose.yaml
- docker/hive/Dockerfile
- src/bin/hive_chain.rs
- src/bin/hive_genesis.rs
- src/bin/katana_genesis.rs
- src/config.rs
- src/eth_provider/constant.rs
- src/eth_provider/error.rs
- src/eth_provider/provider.rs
- src/eth_provider/starknet/kakarot_core.rs
- src/eth_provider/starknet/mod.rs
- src/main.rs
- src/models/felt.rs
- src/models/transaction.rs
- src/test_utils/eoa.rs
- src/test_utils/evm_contract.rs
- src/test_utils/hive/mod.rs
- src/test_utils/katana/genesis.rs
- src/test_utils/tx_waiter.rs
- tests/tests/eth_provider.rs
Resolves: #1233 
Replace starknet_crypto::FieldElement with starknet-types-core
> dev: replace starknet_crypto::FieldElement with starknet-types-core 

- src/eth_provider/database/ethereum.rs
- src/eth_provider/database/types/header.rs
- src/eth_provider/database/types/log.rs
- src/eth_provider/database/types/transaction.rs
- src/eth_provider/provider.rs
- src/retry/mod.rs
- src/test_utils/katana/mod.rs
- src/test_utils/mongo/mod.rs
- tests/tests/eth_provider.rs
- tests/tests/txpool_api.rs
> fuzzer: rm `StoredData` enum from Mongo Fuzzer

- Cargo.lock
- Cargo.toml
- Makefile
- docker-compose.yaml
- docker/hive/Dockerfile
- src/test_utils/eoa.rs
- src/test_utils/hive/mod.rs
- src/test_utils/katana/genesis.rs
> bump ef test and rm starknet api

- Makefile
- docker-compose.yaml
- docker/hive/Dockerfile
- src/eth_provider/starknet/mod.rs
- src/test_utils/constants.rs
- src/test_utils/katana/genesis.rs
- tests/tests/eth_provider.rs
> chore: bump docker-compose deps

- docker-compose.prod.yaml
- docker-compose.staging.yaml
- docker-compose.yaml
- src/retry/mod.rs
Resolves: #NA
Remove extra span and clean docker compose.
> dev: clean tracing

- src/eth_provider/provider.rs
Resolves: #NA
Add tracing level log on call request.
> feat: call request tracing

- indexer/src/types/log.test.ts
- indexer/src/types/log.ts
Time spent on this PR: 60 minutes
Resolves: #1290 
We check if the `fromAddress` field in starknet event is equal to the `KAKAROT_ADDRESS` when reformatting logs in ethereum format.
> dev: check `fromAddress` in starknet event

- Cargo.lock
- Cargo.toml
- src/test_utils/mock_provider.rs
- src/test_utils/mod.rs
- src/tracing/builder.rs
Resolves: #1082 
Added tests to cover all failure cases of the TracerBuilder using a mocked EthereumProvider.
> test: add coverage for all edge cases of the TracerBuilder

- Cargo.lock
- Cargo.toml
- src/providers/eth_provider/database/ethereum.rs
- src/providers/eth_provider/database/types/transaction.rs
> feat: generate arbitrary mock tx with signature

- src/providers/eth_provider/transactions.rs
Resolves: #1343 
Add `ethereum_hash` and `starknet_hash` fields to the event emitted in `send_raw_transaction`
> feat: add ethereum_hash and starknet_hash fields in send_raw_transaction

- src/main.rs
- src/providers/eth_provider/constant.rs
- src/providers/eth_provider/gas.rs
- src/providers/eth_provider/provider.rs
- tests/tests/eth_provider.rs
> dev: refactor namings

- tests/tests/eth_provider.rs
Resolves: #1349 
unit tests for the send_raw_transaction method, ensuring that the mempool correctly validates and handles transactions, including both acceptance of valid transactions and rejection of invalid ones
> feat: add unit tests for the mempool in send_raw_transaction

- src/test_utils/mongo/mod.rs
Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1281
> finalize Mongo Fuzzer reorg

- .github/workflows/kakarot_release.yml
- .github/workflows/rust_test.yml
- docker-compose.prod.yaml
- docker-compose.staging.yaml
- docker-compose.yaml
- docker/hive/Dockerfile
Resolves: #NA
Bump the sink mongo image for release and usages in composes + hive.
> dev: bump mongo sink

- src/lib.rs
- src/pool/mempool.rs
- src/providers/eth_provider/state.rs
- src/providers/sn_provider/mod.rs
- src/providers/sn_provider/starknet_provider.rs
Related https://github.com/kkrt-labs/kakarot-rpc/pull/1360#discussion_r1746616557
> sn-provider: add a wrapper around starknet provider

- Makefile
- src/client/mod.rs
- src/eth_rpc/rpc.rs
- src/pool/mempool.rs
- src/providers/eth_provider/blocks.rs
- src/providers/eth_provider/chain.rs
- src/providers/eth_provider/gas.rs
- src/providers/eth_provider/provider.rs
- src/providers/eth_provider/state.rs
- src/providers/eth_provider/transactions.rs
- src/providers/sn_provider/starknet_provider.rs
- src/test_utils/eoa.rs
- src/test_utils/katana/mod.rs
- src/tracing/mod.rs
- tests/tests/eth_provider.rs
- tests/tests/mempool.rs
Related https://github.com/kkrt-labs/kakarot-rpc/pull/1366#discussion_r1749839658
> provider: embed `StarknetProvider` in `EthDataProvider`

- src/pool/mempool.rs
Resolves: #NA
Improves the current lock mechanism on the account manager to only lock a single account when needed.
> dev: account manager

- src/pool/mempool.rs
Resolves: #NA
The accounts are now iterated only if they have enough balance.
> dev: avoid iterating empty relayers

- .github/workflows/rust_test.yml
- src/bin/hive_chain.rs
- src/client/mod.rs
- src/eth_rpc/api/kakarot_api.rs
- src/eth_rpc/rpc.rs
- src/eth_rpc/servers/kakarot_rpc.rs
- src/main.rs
- src/models/felt.rs
- src/models/transaction.rs
- src/pool/mempool.rs
- src/providers/eth_provider/constant.rs
- src/providers/eth_provider/error.rs
- src/providers/eth_provider/gas.rs
- src/providers/eth_provider/provider.rs
- src/providers/eth_provider/starknet/kakarot_core.rs
- src/providers/eth_provider/starknet/mod.rs
- src/providers/eth_provider/starknet/relayer.rs
- src/providers/eth_provider/state.rs
- src/providers/eth_provider/transactions.rs
- src/providers/sn_provider/starknet_provider.rs
- tests/tests/alchemy_api.rs
- tests/tests/eth_provider.rs
- tests/tests/kakarot_api.rs
- tests/tests/trace_api.rs
- tests/tests/tracer.rs
Time spent on this PR: 2 days
Lays out: #1310 
Execute from outside is added to the RPC, but most tests are skipped (20 in unit tests and hive tests are skipped).
> feat: execute from outside

- src/providers/eth_provider/database/state.rs
Resolves: #NA
Use the join! macro in order to improve make the fetching of the account information concurrent.
> dev: use join! macro

- tests/tests/mempool.rs
Resolves: #1387 
fix the mempool tests using the katana_empty
> fix: mempool tests

- src/providers/eth_provider/starknet/kakarot_core.rs
- src/test_utils/katana/genesis.rs
- tests/tests/eth_provider.rs
> reactivate more tests in the eth provider

- .github/workflows/release.yml
Fixes the release workflow by adding scarb to it.
> fix: release flow

- .github/workflows/release.yml
> fix asdf in release ci

- src/pool/constants.rs
- src/pool/mempool.rs
- src/pool/mod.rs
Resolves: #NA
Lower the threshold for the relayer balance.
> fix: relayer balance

- .github/workflows/release.yml
- .github/workflows/rust_test.yml
- .github/workflows/staging.yml
- .trunk/trunk.yaml
- README.md
- docker/hive/Dockerfile
- docker/rpc/Dockerfile
- src/bin/hive_chain.rs
- src/client/mod.rs
- src/constants.rs
- src/eth_rpc/config.rs
- src/lib.rs
- src/main.rs
- src/pool/mempool.rs
- src/providers/eth_provider/constant.rs
- src/providers/eth_provider/provider.rs
- src/test_utils/katana/mod.rs
- src/tracing/mod.rs
- tests/tests/eth_provider.rs
Resolves: #NA
Updates the chain id, bumps Kakarot to v0.9.1 and reorders some  constants.
> fix: update the chain id

- src/test_utils/katana/genesis.rs
> Update Kakarot to v0.9.2

- src/pool/mempool.rs
- src/providers/eth_provider/starknet/relayer.rs
Resolves: #NA
Adds instrumentation in the relayers and fixes a max fee issue for the relayers.
> chore: improve relayers

- .github/workflows/karnot-deployment.yaml
- deployments/karnot/deployment-config.yaml
Added Karnot Deployment CI file for deploying config & images to Karnot Cloud 
Time spent on this PR: 
Resolves: 
> added: karnot-deployment.yaml for karnot cloud deployment

- .github/workflows/release.yml
- .github/workflows/rust_test.yml
- docker-compose.prod.yaml
- docker-compose.staging.yaml
- docker-compose.yaml
- docker/hive/Dockerfile
Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1433
> bump sink-mongo to 0.9.2

- Cargo.lock
- Cargo.toml
- src/test_utils/katana/mod.rs
- tests/tests/eth_provider.rs
Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1397
Sorry @varun-doshi, had to do the bump of katana and this was included inside
> bump katana to `v1.0.0-alpha.15`

- Cargo.lock
- Cargo.toml
Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1426
> bump cargo to 0.7.1

- src/providers/eth_provider/transactions.rs
Resolves: #NA
Remove the unused Starknet nonce for the transaction count.
> chore: remove sn nonce

- src/providers/eth_provider/gas.rs
- src/providers/eth_provider/provider.rs
- src/providers/eth_provider/state.rs
Resolves: #NA
Renames the methods in order to correctly dispatch the call to `estimate_gas`.
> fix: rename methods

- src/client/mod.rs
Time spent on this PR: 30 min
Resolves: #1475 
Adds logging in the send_raw_transaction.
> obs: send_raw_transaction

- .dockerignore
- .env.example
- Makefile
- docker/hive/Dockerfile
- docker/rpc/Dockerfile
> Update Kakarot to v0.9.3

- .github/workflows/dependencies.yml
Similar to https://github.com/kkrt-labs/keth/pull/72
> add cargo update dependencies workflow

- src/client/mod.rs
- src/eth_rpc/api/eth_api.rs
- src/eth_rpc/api/txpool_api.rs
- src/eth_rpc/servers/eth_rpc.rs
- src/eth_rpc/servers/txpool_rpc.rs
- src/providers/eth_provider/blocks.rs
- src/providers/eth_provider/database/ethereum.rs
- src/providers/eth_provider/database/types/header.rs
- src/providers/eth_provider/database/types/receipt.rs
- src/providers/eth_provider/database/types/transaction.rs
- src/providers/eth_provider/receipts.rs
- src/providers/eth_provider/transactions.rs
- src/providers/eth_provider/tx_pool.rs
- src/providers/pool_provider.rs
- src/test_utils/katana/mod.rs
- src/test_utils/mock_provider.rs
- src/test_utils/mongo/mod.rs
- src/tracing/builder.rs
- tests/tests/debug_api.rs
- tests/tests/txpool_api.rs
This PR is simplifying the usage of some types in the codebase to improve readability and management.
Time spent on this PR: 45 minutes
Resolves: #1398 
Normal
> dev: simplify WithOtherFields<T> usage

- Cargo.lock
- Cargo.toml
- Makefile
- docker-compose.prod.yaml
- docker-compose.staging.yaml
- docker-compose.yaml
- docker/hive/Dockerfile
Resolves: #NA
Prepare release v0.7.5 by bumping dockers and manifest.
> release: prepare v0.7.5

- docker-compose.prod.yaml
#1498 
Bump the versions and addresses for the production docker compose.
> fix: update prod docker compose

- .github/workflows/e2e-pipeline.yml
Resolves: #NA
Correctly install all scarb versions in the CI.
> ci: fix scarb installation
