kkrt-labs/kakarot-rpc

core/src/helpers.rs
core/src/lightclient/mod.rs
docs/methods/eth_getBlockTransactionCountByNumber.md
rpc-call-examples/getBlockTxCountByNumber.hurl
rpc/src/eth_rpc.rs

Implement getBlockTransactionCountByNumber
Time spent on this PR: 0.3
Unimplemented
Returns the number of transactions in a block given a block number.

feat: get block transaction count by number

---

core/src/client/constants.rs
core/src/client/mod.rs
core/src/client/types.rs
core/src/helpers.rs
core/tests/client.rs
rpc/src/eth_rpc.rs
rpc/tests/testing_utils.rs
rustfmt.toml

`cargo fmt` by default preserve the original structure written by the developer.
Using the `Crate` options will enforce a consistent usage of imports across the project
Config partially taken from [reth](https://github.com/paradigmxyz/reth/blob/058349ecf86a41dd71b4916dc28cefa56eb8fb7e/rustfmt.toml)

Add import rules in rust fmt

---

.github/workflows/kakarot_rpc.yml
fly.toml

The RPC Docker image is not built in the CI nor published in a sayajin-labs registry
Image is built on each merge on main and published in sayajin-labs's registry

Add workflow to build and push image to ghcr registry

---

core/src/client/mod.rs

Copy the signature from the calldata into the starknet transaction field.
Closes #109 
Transactions are sent to Starknet with an empty signature field as EOA pulls the signature from the Starknet tx calldata.
Transactions are sent with a filled signature field.
- Add signature to Starknet tx field.
The PR does not currently include tests. Any guidance as to how to add testing would be appreciated.

fix: copy signature from calldata to tx field

---

.github/workflows/kakarot_rpc.yml

current publishing of the rpc image fails in `build_and_publish` job,  it seems to be an authentication error, might be we should try to publish it in our new org name for auth to pass, i.e **kkrt-labs**.
Closes #161 
publish fails on `build_and_publish` probably because of auth failure.
Issue Number: #161 
it should probably pass as the assumption is that it arrives from the change in org name.

fix: fix docker buildx publish error for docker image

---

crates/core/Cargo.toml
crates/core/src/client/constants.rs
crates/core/src/client/helpers.rs
crates/core/src/client/mod.rs
crates/core/src/mock/assert_helpers.rs
crates/core/src/models/mod.rs
crates/rpc/src/eth_rpc.rs

There are multiple places where we are using hardcoded values to mock real data, the pr assembles all such constants in a single `mock_evm_data` module, inside `constants.rs`.
The name of the module comes from the fact that we are using these constants in place of mock values.
As we keep changing these values with real data, we can keep removing these constants as well from the module + now change in their values will also be atomic.
Closes #154 
Currently, we are using hardcoded values in place of constants, whereas we extract them to a single source so that a change to their values is atomic.
Issue Number: #154 
- All mocked hardcoded values have been extracted to constants.
The heuristic used to find these values were:
- Search for …

refactor: extract out all constants being used as hardcoded values or to mock realdata in a single file 🚀 

---

crates/core/src/client/mod.rs

We were using `fold` on the `starknet_contract_address` vector, it is supposed to contain just one field element and that should be the contract address itself, we were using a concatenation technique to query the first value.
It also meant that if the length of this vector is 2 or something else than 1, then we won't be able to catch it, and will keep on concatenating!
The PR adds a better way to do this:
- to check for the length of this Vec  { and report in case there is some error in inspection }
- to query the first element
- shadow the same old variable so that we have a meaningful name for this value
Closes #166 
We are using `fold` to obtain the first value of the `starknet_contract_address` vector, which is not the ideal way to …

dev: fix use of `fold` to get the first element of `starknet_contract_address` 🥷 

---

crates/core/src/client/client_api.rs
crates/core/src/client/constants.rs
crates/core/src/client/mod.rs
crates/rpc/src/eth_rpc.rs

Implements the eth_getTransactionCount API, this will allow fetching nonce for an account and will allow easy use of tools like Metamask.
The mentioned endpoint is not implemented, and a fixed value 3 is returned.
Resolves: #146 
- the real nonce associated with a given EOA is returned

feat: add support for eth_getTransactionCount 🚀

---

crates/core/src/models/transaction.rs

Adds a helper function to check if a Starknet transaction is part of Kakarot.
Time spent on this PR: NA
The check for a Kakarot transaction is coded inside of `to_eth_transaction`.
Resolves: #152 
Extract the logic from `to_eth_transaction` into a separate function, which will allow for better unit testing and reusability.

add a is_kakarot_tx function

---

Cargo.lock
Cargo.toml
crates/core/src/client/config.rs
crates/core/src/client/errors.rs
crates/core/src/client/mod.rs
crates/core/src/mock/wiremock_utils.rs
crates/rpc/Cargo.toml
crates/rpc/src/config.rs
crates/rpc/src/lib.rs
crates/rpc/src/main.rs
crates/rpc/tests/utils.rs

Refactor environment variable parsing to a single file, and move validation to a single function.
As of now every time we need an environment variable, we parse it and then do a `map_err`,  in the future we might need more environment variables, and they might be used in various files { they are already being used in 2 } + some of these variables might only be needed when a special branch of the code is executed, and if not present might panic the service later.
This PR move parsing of all these variables and exposes them as lazy statics, it also provides a validation function, which can be run before the start of the service, if some critical variable is not present, it will panic the service before it even starts. Hence we can also use …

refactor: refactor environment variable handling

---

crates/core/src/client/client_api.rs
crates/core/src/client/mod.rs
crates/core/src/mock/wiremock_utils.rs
crates/core/src/models/block.rs
crates/core/src/models/convertible.rs
crates/core/src/models/event.rs
crates/core/src/models/transaction.rs
crates/core/tests/client.rs
crates/eth-rpc/src/eth_rpc.rs
crates/eth-rpc/src/lib.rs

Refactor `KakarotProvider` trait for seperation of responsibilites
Currently, we have a single `KakarotProvider` trait, which defines methods, that are a combination of Eth methods and Starknet methods, which removes the lines of separation between these individual responsibilities.
Resolves: #198 
- `KakarotProvider` is now a combination of `KakarotEthApi` and `KakarotStarknetUtils`.
- `KakarotEthApi`: All Ethereum-related concerns live here.
- `KakarotStarknetUtils`: All Starknet concerns live here.

refactor: refactor KakarotProvider trait for seperation of responsibilites

---

crates/core/src/client/client_api.rs
crates/core/src/client/mod.rs
crates/core/src/mock/fixtures/responses/transactions/starknet_getTransactionReceipt.json
crates/core/src/models/convertible.rs
crates/core/src/models/event.rs
crates/core/tests/client.rs

Use starknet event wrapper in `transaction_receipt`
We are not leveraging the Starknet Wrapper and the `to_eth_log` method implemented in #174 
Resolves: #215 
- We use the wrapper type for native Starknet event
- We use the `to_eth_log` method
- We filter out non-kakarot events from the log
- ~~Updated mock response file to use correct Kakarot_address, so that the tests don't panic with errors defined [here](https://github.com/kkrt-labs/kakarot-rpc/blob/fd9fbf24da43fdd3dd5fff059dabe0b204758b59/crates/core/src/models/event.rs#L34).~~ { as discovered after review from @jobez , that the file can be left as it is, and will act as a test that we are filtering out Starknet events in the RPC call. }

refactor: use starknet event wrapper in `transaction_receipt`

---

crates/core/src/client/mod.rs
crates/core/src/models/event.rs
crates/core/src/models/felt.rs
crates/core/tests/client.rs

- ✅  Refactoring (no functional changes, no API changes)
Resolves: #213 
going from felt -> ethereum address is implemented via a `try_into` that asserts that the felt doesn't exceed the expected size.

feat: try_into for felt -> address

---

crates/eth-rpc/src/eth_rpc.rs

- ✅  Bugfix
When passing `Option::None` for `block_id` in `get_code`, we get a panic. 
In other places, there is an `unwrap_or` usage and we use that in this method as well.
- ✔️  No

maintain `unwrap_or` for `block_number` in `get_code`

---

crates/core/src/client/api.rs
crates/core/src/client/errors.rs
crates/core/src/client/helpers.rs
crates/core/src/client/mod.rs
crates/core/src/models/block.rs
crates/core/src/models/convertible.rs
crates/core/src/models/event.rs
crates/core/src/models/mod.rs
crates/core/src/models/transaction.rs
crates/core/tests/client.rs

Refactor the errors in order to remove a maximum of instances of `EthApiError::Other`. Also removes a `Result` which wasn't needed.
The codebase uses quite a lot of instances of `EthApiError::Other`. Also contains one unused `Result`.
Resolves: #203 
Removed as much `EthApiError::Other` as possible, by adding `EthApiError:: KakarotDataFilteringError`, `DataDecodingError:: TransactionDecodingError`, `DataDecodingError:: InvalidReturnArrayLength ` and `ConversionError:: Other`. Also removes the unused `Result`.
- Add `EthApiError:: KakarotDataFilteringError`, `DataDecodingError:: TransactionDecodingError`, `DataDecodingError:: InvalidReturnArrayLength ` and `ConversionError:: Other`.
- Remove unused `Result`.
- …

fix: refactor errors

---

crates/core/src/client/api.rs
crates/core/src/client/mod.rs
crates/core/src/client/tests/mod.rs
crates/core/tests/client.rs
crates/eth-rpc/src/eth_rpc.rs

`submit_starknet_transaction` method was part of the `KakarotEthApi` trait, but it is better suited to `KakarotStarknetApi` trait, this PR does this refactor.
It also refactors the `KakarotEthApi` trait so that its methods use Reth types as parameter types wherever required to make it consistent with `EthApi` trait.
- `submit_starknet_transaction` method is part of the `KakarotEthApi`. 
- `KakarotEthApi` has methods whose parameters aren't of `Reth` types, creating inconsistency with the `EthApi` trait's method signatures.
Resolves: #233 , #237 
- `submit_starknet_transaction` method is part of the `KakarotStarknetApi` 
- `KakarotEthApi` has been refactored for methods to use `Reth` types wherever possible.

refactor: refactor `submit_starknet_transaction` our from `KakarotEthApi` to `KakarotStarknetApi`

---

Cargo.toml

blockifier points to dojo's fork's mainbranch, whereas they are currently pointing to a specific commit. 
We depend on the same commit that they do, so we can rely on the power of anime less for stability.
-
-
-

remove branch dependency for blockifier

---

crates/core/src/test_utils/deploy_helpers.rs

Time spent on this PR: .2
was using Default::default() for the nonce value that was being constructed in the ethereum transaction that was being sent in a starknet transaction. this breaks when you try to use the starknet address underpinning the ethereum deploy more than once. 
now we retrieve the nonce of the `eoa_starknet_account` per each deploy
-
-
-

bug-fix/use correct nonce in `deploy_evm_contract`

---

crates/core/src/client/mod.rs
crates/core/tests/client.rs
scripts/PlainOpcodes.s.sol

Time spent on this PR: .1
An EOA address is mapped to a starknet address w/ `compute_starknet_address`, then looked up for a nonce against the provider. When the mapped address doesn't exist, we get a NoContractError.
Resolves: #259 
We match for NoContractError's and map it to a zero, per the evm tooling norms.
-
-
-

map `NoContractError` to zero for `eth_getTransactionCount`

---

Makefile

`make run-dev NETWORK=katana` will
- build kakarot evm
- deploy it to the katana network (assumed to be running)
- start kakarot-rpc with the correct kakarot evm address of the resultant deploy

consolidated flow of building kakarot and deploy and start rpc

---

crates/core/src/client/mod.rs

Time spent on this PR: 0.3
Resolves: #277
When using the RPC with madara, eth_getCode doesn't raise when the queried contract doesn't exist.

Fix getCode should not raise when contract doesn't exist

---

Cargo.lock
Cargo.toml
crates/core/src/test_utils/deploy_helpers.rs
crates/core/tests/client.rs

We bump our dependency on dojo-test-utils. This lets us pass vm steps in the test sequencer constructor.
I also have a pending PR that should make building clean easier/stabler. @Eikix tried building from main without any changes in the dev toml and was seeing this:
```
error: failed to run custom build command for `dojo-test-utils v0.1.0 (/Users/eliastazartes/code/kkrt-labs/dojo/crates/dojo-test-utils)`
Caused by:
process didn't exit successfully: `/Users/eliastazartes/code/kkrt-labs/dojo/target/debug/build/dojo-test-utils-5c0004dea8bf6753/build-script-build` (exit status: 101)
--- stdout
Updating git repository https://github.com/dojoengine/dojo
Running git fetch --verbose --force …
```

bump dojo-test-utils and refactor deploy_helpers w/ vm steps

---

Makefile

I am suggesting to stop deploying kakarot when running `make run-dev` because I often keep a madara open, with
once-for-all deployed Kakarot, but I do kill and restart the RPC.
wdyt?

Stop deploying Kakarot in run-dev

---

crates/core/src/client/mod.rs
crates/core/src/client/tests/mod.rs
foundry.toml

I previously justified the changes to the `transaction_index` default return value in TransactionReceipt. 
A similar deserializatior error happens when trying to use forge create like so:
`forge create  "Counter" --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80`
You would see something like:
```
Deserialization Error: invalid type: null, expected a sequence at line 1 column 177. Response: {"baseFeePerGas":["0x1","0x1","0x1","0x1","0x1","0x1","0x1","0x1","0x1","0x1","0x1"],"gasUsedRatio":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9],"oldestBlock":"0x2b3","reward":null}
```
So we do a similar change to the default value for the 'reward' field. 
I also included a …

changes to allow usage `forge create` and `cast`

---

crates/core/src/client/api.rs
crates/core/src/client/mod.rs
crates/core/src/client/tests/mod.rs
crates/eth-rpc/src/servers/eth_rpc.rs

Currently, when `starknet_provider` doesn't manage to find a transaction, we raise.
However, the eth_rpc doesn't raise on transaction not found.
The proposed modification is too large as it converts any starknet error into a `None` while
we should probably only convert `tx not found`. However, because some RPC don't use consistent error, I've done this as it was easier.
wdyt?

Do not raise when starknet.getTransaction raises

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/client/api.rs
crates/core/src/client/config.rs
crates/core/src/client/errors.rs
crates/core/src/client/helpers.rs
crates/core/src/client/mod.rs
crates/core/src/client/tests/mod.rs
crates/core/src/kakarot/mod.rs
crates/core/src/mock/constants.rs
crates/core/src/mock/wiremock_utils.rs
crates/core/src/models/block.rs
crates/core/src/models/call.rs
crates/core/src/models/event.rs
crates/core/src/models/felt.rs
crates/core/src/models/mod.rs
crates/core/src/models/transaction.rs
crates/core/tests/client.rs
crates/eth-rpc/src/api/eth_api.rs
crates/eth-rpc/src/main.rs
crates/eth-rpc/src/servers/eth_rpc.rs

Add a simulate transaction to the API and implements the json rpc method for `eth_estimateGas`.
Time spent on this PR: 2 days
Resolves: #164 
Route estimate_gas is implemented using the gateway url. 
Currently, given the layout of the `Network` enum, we can only use estimate fee when using the `SequencerGatewayProvider`. Might need to modify it.

feat: simulate transaction

---

.env.example
Makefile

Time spent on this PR: infinite
There was currently a very tragic 'but the forge script works on my computer, you guys' phenomena going on. After witnessing first hand the horror of the same flow not working on other computers (which also unfortunately exist), I made the effort to diff my top level env file from the example.
I was able to reproduce the error cases locally and then narrow it down to adjusting the `PROXY_ACCOUNT_CLASS_HASH`
I then cloned a fresh repo and did the following steps
- have rust and jq installed (need to ensure i have good coverage of this, was just focusing on reproducing/fixing the error cases i saw in two different deploy attempts today)
- in madara
- run `cargo run --release -- …

adjust proxy class hash, default to madara

---

Dockerfile
README.md
docker-compose.katana.yaml
docker-compose.yaml

Time spent on this PR: 0.01
Resolves: #337, #371 
Create a side-car container that does a healthcheck on the `starknet` service that it is ready to accept connections before deploying Kakarot contracts

dev: add docker healthcheck in compose

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/client/errors.rs
crates/core/src/client/mod.rs
crates/core/src/contracts/contract_account.rs
crates/core/src/contracts/erc20/ethereum_erc20.rs
crates/core/src/contracts/erc20/mod.rs
crates/core/src/contracts/erc20/starknet_erc20.rs
crates/core/src/contracts/kakarot.rs
crates/core/src/models/balance.rs
crates/core/src/models/felt.rs
crates/core/tests/client.rs
crates/eth-rpc/src/servers/alchemy_rpc.rs
crates/eth-rpc/src/servers/eth_rpc.rs

Abstract calls to Kakarot ERC20 tokens by wrapping them in a structure.
Resolves: #366 and #361 
Calls to the `balanceOf(Address)` for ERC20's deployed on Kakarot are absctracted into a `EthereumErc20` structure.

feat: erc20.sol

---

.github/workflows/benchmark.yml

Resolves: #420 
This pr makes benchmark only run on `push`.
Benchmark job will only run on push.

feat: update benchmarking workflow to only run `push`

---

CHANGELOG.md
Makefile

Time spent on this PR: 0
Always pulls the image for services with latest tag

dev: `docker-compose` always pulls image for latest tags

---

.github/workflows/benchmark.yml
.github/workflows/changelog.yml
.github/workflows/kakarot_rpc.yml
.github/workflows/lock.yml
.github/workflows/spell_check.yml
.github/workflows/stale.yml
.github/workflows/test.yml
CHANGELOG.md

Add timeout to all github workflows.
Resolves: #439 
- all workflows have a timeout so that they stop if they are running for very long duration
- no need to manually stop workflows

feat: add timeout to all github workflows

---

CHANGELOG.md
benchmarking/scripts/processor.js

In the current benchmarking CI, ofthen there occurs a nonce race, and from my experience, the way to solve it is to decrease the rate at which send the transaction, this PR slightly bumps the delay between two transactions by 150ms, which should probably resolve it, otherwise we would have to move to a custom runner.
- Decreases the rate at which we send transactions which should lower the chance of getting a nonce race.

dev: slightly decrease the rate at which we send transaction

---

.env.example
README.md

Resolves: #496 
Updates the `.env.example` with the latest correct class hash for proxy class account.
The correct class hash has been updated.

fix: update proxy_account_class_hash in `.env.example`

---

crates/core/src/test_utils/bin/dump-katana.rs

Fixes the dump katana script in order to correctly mark the current commit hash used for Kakarot.
Resolves: #NA
The correct commit hash for Kakarot is added in the .katana folder along with the dump.

fix: update the dump katana script

---

crates/core/src/test_utils/bin/dump-katana.rs

Fix the way submodule information is fetched when building the katana dump.
Resolves: #NA
Submodule information is now the one present in the working directory.

fix: dump katana script

---

crates/core/src/test_utils/bin/dump-katana.rs

Removes the quotes from the generated `kakarot_sha` file.
Time spent on this PR: NA
Resolves: #NA
Generated katana dump comes with a sha file. This PR removes the quotes.

fix: remove quotes in sha

---

crates/core/src/test_utils/bin/dump-katana.rs

Appends "-dirty" to the commit hash of Kakarot if the workdir contains local changes.
Resolves: #NA
Adds "-dirty" for a dirty submodule.

feat: check submodule kakarot dirty

---

crates/test-utils/src/deploy_helpers.rs

Resolves: #567 
-  removes reduntant re-assignment of test_environment variable.

dev: remove reduntant assigment of `test_environment` variable

---

crates/core/src/client/config.rs
crates/core/src/client/mod.rs
crates/core/src/mock/mock_starknet.rs
crates/eth-rpc/src/main.rs
crates/test-utils/src/deploy_helpers.rs
crates/test-utils/src/rpc_helpers.rs

Resolves: #566 
The PR renames `StarknetConfig` to `KakarotRpcConfig` as the name is more accurate to what the structure represents.

dev: rename `StarknetConfig` to `KakarotConfig`

---

crates/test-utils/src/bin/dump-katana.rs
crates/test-utils/src/deploy_helpers.rs
crates/test-utils/src/hive_utils/hive/genesis.rs

Resolves: #561 
As mentioned in #561 , we were often reading first from a file to string, and then passing it to serde_json.
serde_json has the following methods:
- [from_reader](https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html)
- [to_writer_pretty](https://docs.rs/serde_json/latest/serde_json/fn.to_writer_pretty.html)
Which can allow reading and writing directly from and to a Reader and a Writer respectively.
This PR also fixes some variables names, where it seems fit.

dev: use `from_reader` and `to_writer_pretty` from serde_json, remove reading from memory to string

---

crates/core/src/client/config.rs
crates/core/src/client/errors.rs
crates/core/src/client/mod.rs
crates/core/src/client/waiter.rs
crates/core/src/contracts/erc20/ethereum_erc20.rs
crates/core/src/contracts/erc20/starknet_erc20.rs
crates/core/src/mock/mock_starknet.rs
crates/core/src/models/balance.rs
crates/core/src/models/block.rs
crates/core/src/models/call.rs
crates/core/src/models/event.rs
crates/core/src/models/felt.rs
crates/core/src/models/signature.rs
crates/core/tests/helpers.rs
crates/eth-rpc/src/config.rs
crates/eth-rpc/src/servers/net_rpc.rs
crates/eth-rpc/src/servers/web3_rpc.rs
crates/test-utils/src/execution/contract.rs
crates/test-utils/src/execution/eoa.rs
crates/test-utils/src/hive_utils/hive/genesis.rs
crates/test-utils/src/hive_utils/types.rs
crates/test-utils/src/sequencer/mod.rs

Time spent on this PR: 2 hours
Related: #584
Applied clippy::nursery lints

dev: clippy::nursery non breaking

---

Makefile
docker-compose.katana.yaml
docker-compose.yaml

@Eikix knows
- Use new env var for defining kakarot's rpc url
- Run katana as daemon
- Force block sealing in katana
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/724)

Use new env var for defining kakarot's rpc url

---

docker/rpc/Dockerfile
src/eth_rpc/mod.rs

1. Add a get /health endpoint
2. Add poetry version to Dockerfile as it installs an older version without that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/752)

add health endpoint

---

src/models/felt.rs

- The usage of `Felt252Wrapper` is simplified via the implementation of `Deref` and `DerefMut`.
- Conversion from Ethereum `Address` type to `Felt252Wrapper` is simplified.

Simplify `Felt252Wrapper` usage via `Deref` and `DerefMut`

---

src/eth_rpc/config.rs
src/test_utils/rpc/mod.rs

Time spent on this PR: 15 min
Resolves: #879 
A new method is introduced in `RPCConfig` structure in order not to depend anymore on the `.env` file for testing purposes.

dev: Decouple test environment from `.env` file

---

src/models/transaction.rs

To accurately convert an RPC transaction type to a primitive transaction type, it's advisable to use the reth `TxType` enum for identification rather than hardcoded numerical values.
Therefore, we begin by attempting to convert the bigint to a u8, raising a conversion error if necessary. Subsequently, we perform a thorough identification based on the `TxType`, addressing all potential scenarios.

Use reth `TxType` in `rpc_transaction_to_primitive`

---

src/eth_provider/provider.rs

Time spent on this PR: 5 min
Currently withdrawals are not supported by the RPC. When studying a block, we therefore check that `withdrawals_root` is indeed either `null` or equal to `EMPTY_ROOT_HASH`. If this is not the case then we return an error saying that withdrawals are not supported.
However, until now an `unwrap_or_default` was done. Which means that if `withdrawals_root` was set to `None` then it was assigned the default value of `B256` which is 0x....00 and which does not correspond to the `EMPTY_ROOT_HASH` so an error was thrown. On the contrary, two scenarios must be accepted without raising an error and this is what is done in this PR:
- The `withdrawals_root` is set to `None`: no error
- The `withdrawals_root` is set to …

Small fix on withdrawals root `EMPTY_ROOT_HASH` check

---

src/eth_provider/provider.rs

Currently, in the `block` function of `EthDataProvider`, the block transactions were retrieved before checking if the `withdrawals_root` was correct. This operation, which is quite expensive, is unnecessary to carry out in the case where we know in advance that the `withdrawals_root` is false and that an error will therefore have to be returned.
The transaction query operation for the block is therefore deported to the end of the function, once we are sure that the `withdrawals_root` is valid or `None`.

Reorder operations in `EthDataProvider` `block` method

---

Cargo.toml
docker-compose.yaml
docker/hive/Dockerfile
src/eth_provider/constant.rs
src/eth_provider/database/types/header.rs
src/eth_provider/database/types/receipt.rs
src/eth_provider/database/types/transaction.rs
src/eth_provider/provider.rs
src/eth_provider/utils.rs
src/eth_rpc/servers/debug_rpc.rs
src/models/block.rs
src/test_utils/fixtures.rs
src/test_utils/katana/mod.rs
src/test_utils/mongo/mod.rs
tests/debug_api.rs
tests/eth_provider.rs

Part of #917.
- This PR introduces fuzzing values to our test suite for debug API. As this PR already introduces quite a few changes, I think it is better to proceed step by step and integrate the fuzzing values on the other tests in a follow up PR.
- There seemed to be a problem recognizing block IDs in our tests due to the formatting (the block ID was always considered a hash because it was represented by the same format `0x{:064x}`. This is corrected in the tests where the parameters are:
- Hash: `0x{:064x}`
- Number: `0x{:016x}`
- The same problem appeared in the RPC itself, in my opinion, when generating filters via `into_filter` with a width of 64 which was revised to 16 for the block numbers which …

Add fuzzer values to test suite

---

docker/hive/Dockerfile
src/eth_provider/provider.rs

With the recent update, the behavior of distinguishing the pending block from `Latest`, `Finalized`, or `Safe` has been introduced. In this scenario, when the tag is `Pending`, it represents the last indexed block. To obtain the block numbers for `Latest`, `Finalized`, or `Safe`, the result of the provider's `block_number` is decremented by one.

Differenciate pending block in `tag_into_block_number`

---

src/config.rs
src/eth_provider/provider.rs
tests/eth_provider.rs

Time spent on this PR: 2h
Resolves: #916
- During the sending of raw transactions, after signature recovering, a pending transaction database is populated before firing a transaction to Starknet for processing. This database collection aims to be able to query the database based on the hash of the transaction before receiving the receipt.
- The recovery of the chain ID with the handling of the error is moved to the start of the function because it is an inexpensive operation compared to the decoding of the transaction. It is therefore better to execute it first before decoding the transaction possibly for nothing if the chain ID is not correct.

dev: improved handling of pending transactions in database

---

src/eth_provider/provider.rs
src/test_utils/eoa.rs
src/test_utils/fixtures.rs
tests/eth_provider.rs

Resolves: #859 
- The case where the bytecode is null is handled in `get_code`. Indeed, when the bytecode is null (and after the other conditions are met), instead of outputting an error, we can simply call the function which gives us the length of the bytecode. If this is zero then we know that the bytecode is null and we can return the default value (as in the case where the contract does not exist).
- A unit test is used to test this functionality with a null bytecode contract deployed for this occasion.

Handle empty bytecode case in `get_code`

---

src/eth_provider/database/mod.rs
src/eth_provider/provider.rs
src/eth_provider/utils.rs

In order to avoid a util `iter_into` method which is perhaps a little too generic and used only to transform query results to the database from value stored to values wrapped, I think it is preferable to implement the equivalent logic directly inside the `Database` wrapper.
So, here I implemented a `get_and_map_to` method which allows you to get stored elements from the database in the form of a vector and convert this vector into a vector of rpc wrapped types via an iterator.

Add `get_and_map_to` to `Database`

---

.trunk/trunk.yaml
Cargo.lock
Cargo.toml
src/eth_rpc/api/debug_api.rs
src/eth_rpc/api/trace_api.rs
src/eth_rpc/servers/debug_rpc.rs
src/eth_rpc/servers/trace_rpc.rs
src/test_utils/fixtures.rs
src/tracing/builder.rs
src/tracing/config.rs
src/tracing/database.rs
src/tracing/mod.rs
tests/tests/trace_api.rs

Time spent on this PR: 3 day
Resolves: #1010
Adds the `debugTraceBlockByNumber` and `debugTraceBlockByHash` endpoints.

feat: debug block

---

src/eth_provider/database/types/header.rs
src/eth_provider/database/types/transaction.rs
src/models/transaction.rs
src/test_utils/mongo/mod.rs

Derive `Arbitrary` for `StoredTransaction` and `StoredHeader`
- `arbitrary_with_optional_fields` are provided in order to ensure that each optional value has a `Some` and not a `None` which would throw an error in our test suite.
- For `StoredTransactionReceipt` we don't use the derivation process because a lot of fields are optional and the `arbitrary_with_optional_fields` function would be similar in size to the current `arbitrary` function so there is no point in going through a derivation at the moment.

derive `Arbitrary` for `StoredTransaction` and `StoredHeader`

---

docker/hive/start.sh

Resolves: #NA
Lengthen the block time for Katana in the hive docker file in order to make the CI more stable. Instability was coming from the variable time it took the apibara indexer to launch. This increase in block time allows for an increased sleep before testing which hopefully increases stability.

dev: improve hive CI

---

src/eth_provider/provider.rs

Resolves: #NA
Due to the current implementation of the Starkware appchain mempool, incoming transactions with similar nonces will be rejected. In order to fix the retry mechanism, we add the retry count to the max fee which changes the Starknet hash and allows the transaction to pass the feeder.

fix: retry by updating the max fee

---

src/tracing/mod.rs

use `with_base_fee` for `TransactionInfo`

---

src/eth_provider/error.rs

ajusted PrecompileInputError and added unauthorizedPrecompile and invalidCairoSelector
Time spent on this PR: 1 hour
Resolves: #1204 
ajusted the error output from "wrong input_length" to "wrong input_len", according to the "precompileInputError" function output from the "errors.cairo". The same for the output of the "addressCollision" function, from "AddressCollision" to "addressCollision".
Added the "unauthorizedPrecompile" and "invalidCairoSelector" into the "EvmError" enum and the conversion impl From<Vec<FieldElement>> for EvmError.

dev: update EvmError

---

src/eth_provider/starknet/kakarot_core.rs
src/models/transaction.rs
src/retry/mod.rs

Resolves: #1272 
This PR modifies the method of retrieving the environment variables WHITE_LISTED_EIP_155_TRANSACTION_HASHES, TRANSACTION_MAX_RETRIES, and RETRY_TX_INTERVAL, switching from a static to a dynamic approach to allow runtime updates.

dev: update statically fetched env vars

---

src/test_utils/katana/genesis.rs
src/test_utils/mongo/mod.rs

rm useless functions in Mongo fuzzer to simplify the logic

---

.github/workflows/kakarot_release.yml
.github/workflows/rust_test.yml
Cargo.lock
Cargo.toml
src/bin/katana_genesis.rs
src/eth_provider/constant.rs
src/eth_provider/starknet/kakarot_core.rs
src/eth_provider/starknet/mod.rs
src/test_utils/hive/mod.rs
src/test_utils/katana/genesis.rs
src/test_utils/mongo/mod.rs
src/test_utils/rpc/mod.rs

Related:
- In Rust 1.80, `LazyCell` and `LazyLock` are stable https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#lazycell-and-lazylock, giving us the opportunity to remove an useless dependency (`static_lazy`).
- Similar issue is raised in reth: https://github.com/paradigmxyz/reth/issues/9799
- `lazy_static` appears to be intended to be deprecated https://github.com/rust-lang-nursery/lazy-static.rs/issues/214

bump rust to 1.80 and rm lazy_static

---

Cargo.lock
Cargo.toml
src/providers/eth_provider/database/types/transaction.rs
src/test_utils/katana/mod.rs
src/test_utils/mongo/mod.rs
tests/tests/debug_api.rs
tests/tests/eth_provider.rs
tests/tests/txpool_api.rs

Related to https://github.com/kkrt-labs/kakarot-rpc/pull/1324, we can now recover a signer properly from the arbitrary transactions generated for tests. As a result, we don't need hardcoded values anymore.
This PR is responsible for removing constants and hardcoded values ​​that are no longer useful.

rm hardcoded mocked tx

---

src/providers/eth_provider/logs.rs
src/providers/eth_provider/mod.rs
src/providers/eth_provider/provider.rs
src/providers/eth_provider/state.rs
src/providers/eth_provider/transactions.rs
src/test_utils/eoa.rs
src/test_utils/mock_provider.rs
tests/tests/debug_api.rs
tests/tests/eth_provider.rs
tests/tests/kakarot_api.rs
tests/tests/trace_api.rs
tests/tests/tracer.rs

Since there are many providers and they are separated in different files, this PR simplifies their import via unification without needing to resort to submodules each time.

provider: facilitate providers import

---

src/providers/eth_provider/database/ethereum.rs
src/providers/eth_provider/database/types/header.rs
src/providers/eth_provider/database/types/transaction.rs
src/test_utils/mongo/mod.rs
tests/tests/txpool_api.rs

More idiomatic and useful to replace `arbitrary_with_optional_fields` by an appropriate `arbitrary` implementation.

tests: replace `arbitrary_with_optional_fields` by `arbitrary` impl

---

src/test_utils/katana/mod.rs
src/test_utils/mongo/mod.rs

In the process of cleaning up our Mongo Fuzzer, `add_hardcoded_block_header_with_base_fee` method is not needed anymore.
Related https://github.com/kkrt-labs/kakarot-rpc/issues/1281

Add hardcoded block header with base fee

---

src/client/mod.rs
src/eth_rpc/servers/eth_rpc.rs
src/main.rs
src/pool/mempool.rs
src/pool/mod.rs
src/providers/eth_provider/provider.rs
src/providers/eth_provider/transactions.rs
src/test_utils/eoa.rs
src/test_utils/katana/mod.rs
src/test_utils/mock_provider.rs
tests/tests/eth_provider.rs
tests/tests/kakarot_api.rs
tests/tests/trace_api.rs
tests/tests/tracer.rs

**Context:**
As a follow-up to #1321, this pull request addresses the circular dependency between the mempool and the provider.
**Changes Introduced:**
1. **Creation of `KakarotTransactions` Trait:**
- The `send_raw_transaction` method has been moved to a new trait called `KakarotTransactions`.
- This trait is implemented for our `EthClient`.
- This design is inspired by the `FullEthApi` trait in the [reth project](https://github.com/paradigmxyz/reth/blob/6f086d1060ede0a015b9257053218d010a7c6c70/crates/rpc/rpc-eth-api/src/helpers/mod.rs#L55-L66), where the trait is implemented for `EthApi`, which itself contains both a provider and a pool.
2. **Separation of Implementations:**
- By upstreaming the `send_raw_transaction` method, we start to differentiate between the Client's …

Add `KakarotTransactions` trait to upstream `send_raw_transaction`

---

src/client/mod.rs
src/pool/validate.rs
src/providers/eth_provider/blocks.rs
src/providers/eth_provider/database/ethereum.rs
src/providers/eth_provider/provider.rs
tests/tests/mempool.rs

Resolves: #NA
Create a new `EthDatabase` for fetching database information for each transaction.

fix: mempool

---

indexer/src/main.ts
indexer/src/types/interfaces.ts
indexer/src/types/storeItem.ts

Time spent on this PR: 2h30
Resolves: #1187 
- Changed return statements to array filters
- Moved object mutations from map to forEach

cleanup indexer transform function

---

Makefile
src/client/mod.rs
src/eth_rpc/rpc.rs
src/providers/eth_provider/provider.rs
src/providers/eth_provider/tx_pool.rs
src/providers/pool_provider.rs
src/test_utils/fixtures.rs
src/test_utils/katana/mod.rs
src/test_utils/mock_provider.rs
tests/tests/mempool.rs
tests/tests/txpool_api.rs

Follow up on https://github.com/kkrt-labs/kakarot-rpc/pull/1385
Also related https://github.com/kkrt-labs/kakarot-rpc/issues/1391

re-activate txpool API

---

indexer/src/types/transaction.test.ts
indexer/src/utils/filter.test.ts

reactivate indexer tests

---

docker-compose.sepolia.yaml
indexer/src/constants.ts
indexer/src/main.ts

This PR fixes a couple of small configuration errors in the Sepolia docker-compose file:
- Rename `APIBARA_AUTH_TOKEN` to `AUTH_TOKEN`.
- The `STREAM_URL` requires the protocol (in this case `https`) to know whether or not to enable TLS.
Time spent on this PR: 10 minutes
The Sepolia docker compose setup is now indexing data.

Fix indexer's sepolia docker config

---

Cargo.toml
src/pool/mempool.rs
src/providers/eth_provider/database/types/receipt.rs

Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1441

AccountManager: implement `start_nonce_updater`

---

Cargo.toml
src/pool/mempool.rs

Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1447

randomize relayers round

---

src/eth_rpc/api/alchemy_api.rs
src/eth_rpc/api/debug_api.rs
src/eth_rpc/api/eth_api.rs
src/eth_rpc/api/kakarot_api.rs
src/eth_rpc/api/net_api.rs
src/eth_rpc/api/trace_api.rs
src/eth_rpc/api/web3_api.rs
src/eth_rpc/servers/alchemy_rpc.rs
src/eth_rpc/servers/debug_rpc.rs
src/eth_rpc/servers/eth_rpc.rs
src/eth_rpc/servers/net_rpc.rs
src/eth_rpc/servers/trace_rpc.rs
src/eth_rpc/servers/txpool_rpc.rs
src/eth_rpc/servers/web3_rpc.rs

Type aliases can be confusing and it's a better practice to use the path name directly.

use `RpcResult` instead of type alias

---

.vscode/settings.json
src/providers/eth_provider/provider.rs
tests/tests/txpool_api.rs

Our rust analyzer is very slow and crashes a lot. 
To try to limit this, check.command is set to check (default) value as per https://rust-analyzer.github.io/manual.html#vs-code
- This limits computation costs by not applying clippy each time (which can be run manually when needed via `cargo clippy` command)

rust analyzer check.command check

---

src/pool/mempool.rs

Resolves: #940 
Batches the RPC requests made to the starknet provider for the nonce of the relayers.

feat: batch nonce relayers requests

---

Makefile
src/eth_rpc/servers/kakarot_rpc.rs
src/providers/eth_provider/constant.rs
tests/tests/kakarot_api.rs

Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1490

add kakarot address in `Constant`

---

src/main.rs

Resolves: #1409 
The minimal base fee of the pool is set to the base fee of the execution layer at start up of the RPC.

dev: set minimal base fee at start up

---

src/bin/hive_chain.rs
src/main.rs
src/pool/mempool.rs
src/providers/eth_provider/starknet/relayer.rs
src/test_utils/eoa.rs
tests/tests/eth_provider.rs

Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1502

nonce management: query nonce on-chain before relaying tx

---

src/client/mod.rs
src/eth_rpc/servers/eth_rpc.rs

Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1515

tracing error level WARN in `send_raw_transaction`

---

Makefile
src/bin/hive_chain.rs
src/client/mod.rs
src/pool/mempool.rs
src/providers/eth_provider/database/ethereum.rs
src/providers/eth_provider/database/filter.rs
src/providers/eth_provider/database/mod.rs
src/providers/eth_provider/database/types/transaction.rs
src/providers/eth_provider/starknet/relayer.rs
src/test_utils/eoa.rs
tests/tests/eth_provider.rs

Should close https://github.com/kkrt-labs/kakarot-rpc/issues/1521

add starknet transaction hash to `transaction_by_hash`

---

.github/workflows/e2e-pipeline.yml
deployments/karnot/deployment-config.yaml
docker-compose.prod.yaml
docker-compose.staging.yaml
docker-compose.yaml

feat: prepare v0.7.6

---

scripts/e2e_pipeline.sh

There is a new couple of env variables in kakarot
We need them in e2e tests

fix add relayer in e2e tests

---

Makefile

Time spent on this PR: 2h
When trying to install kakarot-rpc, I faced a several issues with kakarot dependencies:
- compilation failed because scarb was not installed
- compilation failed because I downloaded scarb with curl instead of adsm and got wrong version
- compilation failed because I didn't have foundry
After a few lookups in kakarot code, I saw that there is a `setup` command that checks everything, we should call it during the setup of kakarot-rpc.
I guess other people didn't face this because they installed kakarot before installing kakarot-rpc

chore: use setup from kakarot makefile to ease install

---

deployments/karnot/deployment-config.yaml

update version v0.7.6-2 for deploy staging
